
package cn.com.nd.momo.api.util;

/**
 * 多音节，从0x5e67到0x6ECE
 * 
 * @author chenjp
 */
public class MultiPinYin2 {
    public static String[] pinyinArray = null;

    private MultiPinYin2() {
    };

    static {
        if (null == pinyinArray) {
            pinyinArray = new String[] {
                    "qiao", "dan", "fen", "meng", "bang",
                    "chou,dao", "mie", "chu", "jie", "xian", "lan", "gan",
                    "ping", "nian", "jian", "bing", "bing", "xing", "gan",
                    "yao", "huan", "you", "you", "ji", "guang", "pi", "ting",
                    "ze", "guang", "zhuang", "mo", "qing", "bi", "qin", "dun",
                    "chuang", "gui", "ya", "bai", "jie", "xu", "lu", "wu",
                    "none", "ku", "ying", "di,de", "pao", "dian", "ya", "miao",
                    "geng", "ci", "fu", "tong", "pang", "fei", "xiang", "yi",
                    "zhi", "tiao", "zhi", "xiu", "du,duo", "zuo", "xiao", "tu",
                    "gui", "ku", "pang,mang", "ting", "you", "bu", "bing",
                    "cheng", "lai", "bi,bei", "ji", "an", "shu", "kang",
                    "yong", "tuo", "song", "shu", "qing", "yu", "yu", "miao",
                    "sou", "ce,ci", "xiang", "fei", "jiu", "he", "hui", "liu",
                    "sha,xia", "lian", "lang", "sou", "jian", "pou", "qing",
                    "jiu", "jiu", "qin,jin", "ao", "kuo", "lou", "yin", "liao",
                    "dai", "lu", "yi", "chu", "chan", "tu", "si", "xin",
                    "miao", "chang", "wu", "fei", "guang", "none", "guai",
                    "bi", "qiang", "xie", "lin", "lin", "liao", "lu", "none",
                    "ying", "xian", "ting", "yong", "li", "ting", "yin", "xun",
                    "yan", "ting", "di", "po", "jian", "hui", "nai", "hui",
                    "gong", "nian", "kai", "bian", "yi", "qi", "nong,long",
                    "fen", "ju", "yan", "yi", "zang,zhuang", "bi", "yi", "yi",
                    "er", "san", "shi", "er", "shi", "shi", "gong", "diao",
                    "yin", "hu", "fu", "hong", "wu", "tui", "chi", "qiang",
                    "ba", "shen", "di", "zhang", "jue", "tao", "fu", "di",
                    "mi", "xian", "hu", "chao", "nu", "jing", "zhen", "yi",
                    "mi", "quan", "wan", "shao", "ruo", "xuan", "jing", "diao",
                    "zhang", "jiang", "qiang,jiang", "beng", "dan,tan",
                    "qiang,jiang", "bi", "bi", "she", "dan,tan", "jian", "gou",
                    "none", "fa", "bi", "kou", "none", "bie", "xiao",
                    "dan,tan", "kuang", "qiang,jiang", "hong", "mi", "kuo",
                    "wan", "jue", "ji", "ji", "gui", "dang", "lu", "lu",
                    "tuan", "hui", "zhi", "hui", "hui", "yi", "yi", "yi", "yi",
                    "huo", "huo", "shan", "xing", "zhang", "tong", "yan",
                    "yan", "yu", "chi", "cai", "biao", "diao", "bin", "peng",
                    "yong", "piao", "zhang", "ying", "chi", "chi", "zhuo",
                    "tuo", "ji", "pang,fang", "zhong", "yi", "wang", "che",
                    "bi", "di", "ling", "fu", "wang", "zheng", "cu", "wang",
                    "jing", "dai", "xi", "xun", "hen", "yang", "huai,hui",
                    "lu:", "hou", "wang", "cheng", "zhi", "xu", "jing", "tu",
                    "cong", "none", "lai", "cong", "de,dei", "pai", "xi",
                    "none", "qi", "chang", "zhi", "cong,zong", "zhou", "lai",
                    "yu", "xie", "jie", "jian", "chi,shi", "jia", "bian",
                    "huang", "fu", "xun", "wei", "pang", "yao", "wei", "xi",
                    "zheng", "piao", "chi", "de", "zheng", "zhi,zheng", "bie",
                    "de", "chong", "che", "jiao", "wei", "jiao", "hui", "mei",
                    "long", "xiang", "bao", "qu", "xin", "xin", "bi", "yi",
                    "le", "ren", "dao", "ding", "gai", "ji", "ren", "ren",
                    "chan", "tan", "te", "te,tui,tei", "gan", "qi", "dai",
                    "cun", "zhi", "wang", "mang", "xi", "fan", "ying", "tian",
                    "min", "min", "zhong", "chong", "wu", "ji", "wu", "xi",
                    "ye", "you", "wan", "zong", "zhong,song", "kuai", "yu",
                    "bian", "zhi", "chi", "cui", "chen", "tai", "tun", "qian",
                    "nian", "hun", "xiong", "niu,nu:", "wang", "xian", "xin",
                    "kang", "hu", "kai", "fen", "huai", "tai", "song", "wu",
                    "ou", "chang", "chuang", "ju", "yi", "bao", "chao", "min",
                    "pi", "zuo", "zen", "yang", "kou", "ban", "nu", "nao",
                    "zheng", "pa", "bu", "tie", "hu", "hu", "ju", "da",
                    "lian,ling", "si,sai", "zhou", "di", "dai", "yi", "tu",
                    "you", "fu", "ji", "peng", "xing", "yuan", "ni", "guai",
                    "fu,fei", "xi", "bi", "you", "qie,que", "xuan", "zong",
                    "bing", "huang", "xu", "chu", "pi", "xi", "xi", "tan",
                    "none", "zong", "dui", "none", "none", "yi", "chi",
                    "nen,ren,nin", "xun", "shi", "xi", "lao", "heng", "kuang",
                    "mou,mu", "zhi", "xie", "lian", "tiao", "huang", "die",
                    "hao", "kong", "gui", "heng", "xi", "xiao", "shu",
                    "sai,si", "hu", "qiu", "yang", "hui", "hui", "chi", "jia",
                    "yi", "xiong", "guai", "lin", "hui", "zi", "xu", "chi",
                    "xiang", "nu:", "hen", "en", "ke,que", "dong,tong", "tian",
                    "gong", "quan", "xi", "qia", "yue", "peng", "ken", "de",
                    "hui", "e,wu", "none", "tong", "yan", "kai", "ce", "nao",
                    "yun", "mang", "yong", "yong", "juan", "mang", "kun",
                    "qiao", "yue", "yu", "yu", "jie", "xi", "zhe,qi", "lin",
                    "ti", "han", "hao", "qie", "ti", "bu", "yi", "qian", "hui",
                    "xi", "bei", "man", "yi", "heng", "song", "quan", "cheng",
                    "kui,li", "wu", "wu", "you", "li", "liang", "huan", "cong",
                    "yi", "yue", "li", "nin", "nao", "e,wu", "que", "xuan",
                    "qian", "wu", "min", "cong", "fei", "bei", "de", "cui",
                    "chang", "men", "li", "ji", "guan", "guan", "xing", "dao",
                    "qi", "kong", "tian", "lun", "xi", "kan", "kun", "ni",
                    "qing", "chou", "dun", "guo", "chan", "jing", "wan",
                    "yuan", "jin", "ji", "lin", "yu", "huo", "he", "quan",
                    "yan", "ti", "ti", "nie", "wang", "chuo", "hu", "hun",
                    "xi", "chang", "xin", "wei", "hui", "e,wu", "rui", "zong",
                    "jian", "yong", "dian", "ju", "can", "cheng", "de", "bei",
                    "qie", "can", "dan", "guan", "duo", "nao", "yun", "xiang",
                    "zhui", "die", "huang", "chun", "qiong", "re", "xing",
                    "ce", "bian", "hun", "zong", "ti", "qiao", "chou", "bei",
                    "xuan", "wei", "ge", "qian", "wei", "yu", "yu", "bi",
                    "xuan", "huan", "min", "bi", "yi", "mian", "yong",
                    "kai,qi", "dang", "yin", "e", "chen", "mou", "qia", "ke",
                    "yu", "ai", "qie", "yan", "nuo", "gan", "yun", "zong",
                    "sai", "leng", "fen", "none", "kui", "kui", "que", "gong",
                    "yun", "su", "su", "qi", "yao", "song", "huang", "none",
                    "gu", "ju", "chuang", "ta", "xie", "kai", "zheng", "yong",
                    "cao", "sun", "shen", "bo", "kai", "yuan", "xie", "hun",
                    "yong", "yang", "li", "sao", "tao", "yin", "ci", "xu",
                    "qian,qie", "tai", "huang", "yun", "shen", "ming", "none",
                    "she", "cong", "piao", "mo", "mu", "guo", "chi", "can",
                    "can", "can", "cui", "min", "ni,te", "zhang", "tong", "ao",
                    "shuang", "man", "guan", "que", "zao", "jiu", "hui", "kai",
                    "lian", "ou", "song", "jin", "yin", "lu:", "shang", "wei",
                    "tuan", "man", "qian", "zhe", "yong", "qing", "kang", "di",
                    "zhi", "lu:", "juan", "qi", "qi", "yu", "ping", "liao",
                    "zong", "you", "chuang", "zhi", "tong", "cheng", "qi",
                    "qu", "peng", "bei", "bie", "chun", "jiao", "zeng", "chi",
                    "lian", "ping", "kui", "hui", "qiao", "cheng", "yin",
                    "yin", "xi", "xi", "dan", "tan", "duo", "dui", "dui", "su",
                    "jue", "ce", "xiao", "fan", "fen", "lao", "lao", "chong",
                    "han", "qi", "xian", "min", "jing", "liao", "wu", "can",
                    "jue", "chou", "xian", "tan", "sheng", "pi", "yi", "chu",
                    "xian", "nao", "dan", "tan", "jing", "song", "han", "jiao",
                    "wei", "huan", "dong", "qin", "qin", "qu", "cao", "ken",
                    "xie", "ying", "ao", "mao", "yi", "lin", "se", "jun",
                    "huai", "men", "lan", "ai", "lin", "yan", "gua", "xia",
                    "chi", "yu", "yin", "dai", "meng", "ai", "meng", "dui",
                    "qi", "mo", "lan", "men", "chou", "zhi", "nuo", "nuo",
                    "yan", "yang", "bo", "zhi", "xing", "kuang", "you", "fu",
                    "liu", "mie", "cheng", "none", "chan", "meng", "lan",
                    "huai", "xuan", "rang", "chan", "ji", "ju", "huan",
                    "she,zhe", "yi", "lian", "nan", "mi", "tang", "jue",
                    "gang", "gang,zhuang", "zhuang", "ge", "yue", "wu", "jian",
                    "xu,qu", "shu", "rong", "xi,hu", "cheng", "wo", "jie",
                    "ge", "jian", "qiang", "huo", "qiang", "zhan", "dong",
                    "qi", "jia", "die", "cai", "jia", "ji", "shi,chi", "kan",
                    "ji", "kui", "gai", "deng", "zhan", "chuang,qiang", "ge",
                    "jian", "jie", "yu", "jian", "yan", "lu", "xi,hu", "zhan",
                    "xi", "xi,hu", "chuo", "dai", "qu", "hu", "hu", "hu", "e",
                    "shi", "li", "mao", "hu", "li", "fang", "suo", "bian,pian",
                    "dian", "jiong", "shang", "yi", "yi", "shan", "hu", "fei",
                    "yan", "shou", "shou", "cai", "zha,za", "qiu", "le", "pu",
                    "ba,pa", "da", "reng", "fu,bi", "none", "zai", "tuo",
                    "zhang", "diao", "kang,gang", "yu", "ku", "han", "shen",
                    "cha", "chi", "gu", "kou", "wu", "tuo", "qian", "zhi",
                    "cha", "kuo", "men", "sao", "yang", "niu", "ban", "che",
                    "rao", "xi", "qian", "ban,pan", "jia", "yu", "fu", "ao",
                    "xi", "pi", "zhi", "zi", "e", "dun", "zhao", "cheng", "ji",
                    "yan", "kuang", "bian", "chao", "ju", "wen", "hu", "yue",
                    "jue", "ba", "qin", "zhen", "zheng", "yun", "wan", "na",
                    "yi", "shu", "zhua", "pou", "tou", "dou", "kang",
                    "zhe,she", "pou", "fu", "pao", "ba", "ao", "ze,zhai",
                    "tuan", "kou", "lun", "qiang", "none", "hu", "bao", "bing",
                    "zhi", "peng", "tan", "pu", "pi", "tai", "yao", "zhen",
                    "zha", "yang", "bao", "he", "ni", "yi", "di", "chi", "pi",
                    "za", "mo,ma", "mo", "chen,shen", "ya", "chou", "qu",
                    "min", "chu", "jia", "fu,bi", "zha", "zhu", "dan",
                    "chai,ca", "mu", "nian", "la", "fu", "pao", "ban", "pai",
                    "lin", "na", "guai", "qian", "ju", "tuo,ta", "ba", "tuo",
                    "tuo", "ao,niu,yao", "ju", "zhuo", "pan,pin", "zhao",
                    "bai", "bai", "di", "ni", "ju", "kuo", "long", "jian",
                    "qia", "yong", "lan", "ning", "bo", "ze,zhai", "qian",
                    "hen", "kuo,gua", "shi", "jie", "zheng", "nin", "gong",
                    "gong", "quan", "shuan", "tun", "zan", "kao", "chi", "xie",
                    "ce", "hui", "pin", "zhuai,ye", "shi,she", "na", "bo",
                    "chi", "gua", "zhi", "kuo", "duo", "duo", "zhi", "qie",
                    "an", "nong,long", "zhen", "ge", "jiao", "kua", "dong",
                    "ru,na", "tiao", "lie", "zha", "lu:", "die", "wa", "jue",
                    "none", "ju", "zhi", "luan", "ya", "wo,zhua", "ta",
                    "xie,jia", "nao", "dang", "jiao", "zheng", "ji", "hui",
                    "xian", "none", "ai", "tuo", "nuo", "cuo", "bo", "geng",
                    "ti", "zhen", "cheng", "suo", "suo,sa,sha", "keng", "mei",
                    "long,nong", "ju", "peng", "jian", "yi", "ting", "shan",
                    "nuo", "wan", "xie,jia,xia", "cha", "feng", "jiao", "wu",
                    "jun", "jiu", "tong", "kun", "huo", "tu", "zhuo", "pou",
                    "lu:,luo", "ba", "han", "shao", "nie", "juan", "she",
                    "shu", "ye", "jue", "bu", "huan", "bu", "jun", "yi",
                    "zhai", "lu:", "sou", "tuo", "lao", "sun", "bang", "jian",
                    "huan", "dao", "none", "wan", "qin", "peng", "she", "lie",
                    "min", "men", "fu", "bai", "ju", "dao", "wo", "ai", "juan",
                    "yue", "zong", "chen", "chui", "jie", "tu", "ben", "na",
                    "nian", "nuo", "zu", "wo", "xi,qi", "xian", "cheng",
                    "dian", "sao", "lun", "qing", "gang", "duo", "shou",
                    "diao", "pou", "di", "zhang", "gun", "ji", "tao", "qia",
                    "qi", "pai", "shu", "qian", "ling", "ye,yi", "ya", "jue",
                    "zheng", "liang", "gua", "yi", "huo", "shan", "ding",
                    "lu:e", "cai", "tan", "che", "bing", "jie", "ti", "kong",
                    "tui", "yan", "cuo", "zou", "ju", "tian", "qian", "ken",
                    "bai,bo", "shou,pa", "jie", "lu", "guai,guo", "none",
                    "none", "zhi", "dan,shan", "none", "chan,shan,can", "sao",
                    "guan", "peng", "yuan", "nuo", "jian", "zheng", "jiu",
                    "jian", "yu", "yan", "kui", "nan", "hong", "rou", "pi",
                    "wei", "sai", "zou", "xuan", "miao", "ti,di,shi", "nie",
                    "cha", "shi", "zong", "zhen", "yi", "shun", "heng", "bian",
                    "yang", "huan", "yan", "zan", "an", "xu,ju", "ya", "wo",
                    "ke", "chuai", "ji,jie", "ti", "la", "la", "cheng", "kai",
                    "jiu", "jiu", "tu", "jie", "hui", "geng", "chong", "shuo",
                    "she,die", "xie", "yuan", "qian", "ye", "cha", "zha",
                    "bei", "yao", "none", "none", "lan", "wen", "qin", "chan",
                    "ge", "lou", "zong", "geng", "jiao", "gou", "qin", "yong",
                    "que", "chou", "chuai", "zhan", "sun", "sun", "bo", "chu",
                    "rong", "bang,peng", "cuo", "sao", "ke", "yao", "dao",
                    "zhi", "nu", "xie", "jian", "sou", "qiu", "gao", "xian",
                    "shuo", "sang", "jin", "mie", "e", "chui", "nuo", "shan",
                    "ta", "jie", "tang", "pan", "ban", "da", "li", "tao", "hu",
                    "zhi", "wa", "xia", "qian", "wen", "qiang,chuang", "chen",
                    "zhen", "e", "xie", "nuo", "quan", "cha", "zha", "ge",
                    "wu", "en", "she", "gong", "she", "shu", "bai", "yao",
                    "bin", "sou", "tan", "sha", "chan", "suo", "liao", "chong",
                    "chuang", "guo,guai", "bing", "feng", "shuai", "di", "qi",
                    "none", "zhai,zhe", "lian", "cheng", "chi", "guan", "lu",
                    "luo", "lou", "zong", "gai,xi", "hu", "zha", "chuang",
                    "tang", "hua", "cui", "nai", "mo,ma", "jiang", "gui",
                    "ying", "zhi", "ao", "zhi", "chi", "man", "shan", "kou",
                    "shu", "suo", "tuan", "zhao", "mo", "mo", "zhe",
                    "chan,shan", "keng", "biao", "jiang", "yin", "gou", "qian",
                    "liao", "ji", "ying", "jue", "pie", "pie", "lao", "dun",
                    "xian", "ruan", "kui", "zan", "yi", "xian", "cheng",
                    "cheng", "sa", "nao", "heng", "si", "han", "huang", "da",
                    "zun", "nian", "lin", "zheng", "hui", "zhuang,chuang",
                    "jiao", "ji", "cao", "dan", "dan,shan", "che", "bo", "che",
                    "jue", "xiao", "liao", "ben", "fu", "qiao", "bo",
                    "cuo,zuo", "zhuo", "zhuan", "tuo", "pu", "qin", "dun",
                    "nian", "none", "xie", "lu", "jiao", "cuan", "ta", "han",
                    "qiao", "zhua,wo", "jian", "gan", "yong", "lei", "kuo",
                    "lu", "shan", "zhuo", "ze,zhai", "pu", "chuo", "ji",
                    "dang", "se", "cao", "qing", "jing", "huan", "jie", "qin",
                    "kuai", "dan", "xie", "ge", "pi", "bo,bai", "ao", "ju",
                    "ye", "none", "none", "sou", "mi", "ji", "tai", "zhuo",
                    "dao", "xing", "lan", "ca", "ju", "ye", "ru", "ye", "ye",
                    "ni", "huo", "ji", "bin", "ning", "ge", "zhi", "jie",
                    "kuo", "mo,ma", "jian", "xie", "lie", "tan", "bai", "sou",
                    "lu", "lu:e", "rao", "zhi", "pan", "yang", "lei", "sa",
                    "shu", "zan,cuan", "nian", "xian", "jun", "huo", "lu:e",
                    "la", "han", "ying", "lu", "long", "qian", "qian",
                    "zan,cuan", "qian", "lan", "san", "ying", "mei", "rang",
                    "chan", "none", "cuan", "xie", "she", "luo", "jun", "mi",
                    "li", "zan,cuan", "luan", "tan", "zuan", "li", "dian",
                    "wa", "dang", "jiao,gao", "jue", "lan", "li", "nang",
                    "zhi", "gui", "gui", "qi", "xin", "po", "po", "shou",
                    "kao", "you", "gai", "gai", "gong", "gan", "ban", "fang",
                    "zheng", "bo", "dian", "kou", "min", "wu", "gu", "ge",
                    "ce", "xiao", "mi", "chu", "ge", "di", "xu", "jiao", "min",
                    "chen", "jiu", "shen", "duo", "yu", "chi", "ao", "bai",
                    "xu", "jiao", "duo", "lian", "nie", "bi", "chang,tang",
                    "dian", "duo", "yi", "gan", "san", "ke", "yan", "dun,dui",
                    "qi", "dou", "xiao", "duo", "jiao", "jing", "yang", "xia",
                    "hun,min", "shu,shuo", "ai", "qiao", "ai", "zheng", "di",
                    "zhen", "fu", "shu,shuo", "liao", "qu", "xiong", "xi",
                    "jiao", "none", "qiao", "zhuo", "yi,du", "lian", "bi",
                    "li", "xue", "xiao", "wen", "xue", "qi,ji", "qi,ji",
                    "zhai", "bin", "jue", "zhai", "lang", "fei", "ban", "ban",
                    "lan", "yu", "lan", "wei", "dou", "sheng", "liao", "jia",
                    "hu", "xie,xia", "jia", "yu", "zhen", "jiao", "wo",
                    "tiao,tou", "dou", "jin", "chi", "yin", "fu", "qiang",
                    "zhan", "qu,ju", "zhuo", "zhan", "duan", "zhuo", "si",
                    "xin", "zhuo", "zhuo", "qin", "lin", "zhuo", "chu", "duan",
                    "zhu", "fang", "xie", "hang", "wu,yu", "shi", "pei", "you",
                    "none", "pang,bang", "qi", "zhan", "mao", "lu:", "pei",
                    "pi", "liu", "fu", "fang", "xuan", "jing", "jing", "ni",
                    "zu", "zhao", "yi", "liu", "shao", "jian", "none", "yi",
                    "qi", "zhi", "fan", "piao", "fan", "zhan", "guai", "sui",
                    "yu", "wu,mo", "ji", "ji", "ji", "huo", "ri", "dan", "jiu",
                    "zhi", "zao", "xie", "tiao", "xun", "xu", "ga", "la",
                    "gan", "han", "tai", "di", "xu", "chan", "shi", "kuang",
                    "yang", "shi", "wang", "min", "min", "tun", "chun", "wu",
                    "yun", "bei", "ang", "ze", "ban", "jie", "kun", "sheng",
                    "hu", "fang", "hao", "gui", "chang", "xuan", "ming", "hun",
                    "fen", "qin", "hu", "yi", "xi", "xin", "yan", "ze", "fang",
                    "tan", "shen", "ju", "yang", "zan", "bing", "xing", "ying",
                    "xuan", "pei", "zhen", "ling", "chun", "hao", "mei", "zuo",
                    "mo", "bian", "xu", "hun", "zhao", "zong", "shi", "shi",
                    "yu", "fei,fu", "die", "mao", "ni", "chang", "wen", "dong",
                    "ai", "bing", "ang", "zhou", "long", "xian", "kuang",
                    "tiao", "chao,zhao", "shi", "huang", "huang", "xuan",
                    "kui", "xu,kua", "jiao", "jin", "zhi", "jin", "shang",
                    "tong", "hong", "yan", "gai", "xiang", "shai", "xiao",
                    "ye", "yun", "hui", "han", "han", "jun", "wan", "xian",
                    "kun", "zhou", "xi", "sheng,cheng", "sheng", "bu", "zhe",
                    "zhe", "wu", "han", "hui", "hao", "chen", "wan", "tian",
                    "zhuo", "zui", "zhou", "pu", "jing,ying", "xi", "shan",
                    "yi", "xi", "qing", "qi", "jing", "gui", "zhen", "yi",
                    "zhi", "an", "wan", "lin", "liang", "chang", "wang",
                    "xiao", "zan", "none", "xuan", "geng", "yi", "xia", "yun",
                    "hui", "fu", "min", "kui", "he", "ying", "du", "wei",
                    "shu", "qing", "mao", "nan", "jian", "nuan", "an", "yang",
                    "chun", "yao", "suo", "pu", "ming", "jiao", "kai", "gao",
                    "weng", "chang", "qi", "hao", "yan", "li", "ai", "ji",
                    "gui", "men", "zan,zhan", "xie", "hao", "mu", "mo", "cong",
                    "ni", "zhang", "hui", "bao,pu", "han", "xuan", "chuan",
                    "liao", "xian", "dan", "jing", "pie", "lin", "tun", "xi",
                    "yi", "ji", "kuang", "dai", "ye", "ye", "li", "tan",
                    "tong", "xiao", "fei", "qin", "zhao", "hao", "yi", "xiang",
                    "xing", "sen", "jiao", "bao", "jing", "none", "ai", "ye",
                    "ru", "shu", "meng", "xun", "yao,yue", "pu,bao", "li",
                    "chen", "kuang", "die", "none", "yan", "huo", "lu", "xi",
                    "rong", "long", "nang", "luo", "luan", "shai", "tang",
                    "yan", "chu", "yue", "yue", "qu", "ye,zhuai,yi", "geng",
                    "zhuai", "hu", "he", "shu", "cao", "cao", "sheng", "man",
                    "ceng,zeng", "zeng,ceng", "ti", "zui", "can", "xu",
                    "hui,kuai", "yin", "qie", "fen", "pi,bi", "yue", "you",
                    "ruan", "peng", "ban", "fu", "ling", "fei", "qu", "none",
                    "nu:", "tiao", "shuo", "zhen", "lang", "lang", "juan,zui",
                    "ming", "huang", "wang", "tun", "chao,zhao", "ji,qi",
                    "qi,ji", "ying", "zong", "wang", "tong", "lang", "none",
                    "meng", "long", "mu", "deng", "wei", "mo", "ben", "zha",
                    "zhu", "shu,zhu", "none", "zhu", "ren", "ba", "po,piao,pu",
                    "duo", "duo", "dao", "li", "qiu", "ji", "jiu", "bi", "xiu",
                    "ting", "ci", "sha", "none", "za", "quan", "qian", "yu",
                    "gan", "wu", "cha", "shan", "xun", "fan", "wu", "zi", "li",
                    "xing", "cai", "cun", "ren", "shao,biao", "zhe", "di",
                    "zhang", "mang", "chi", "yi", "gu", "gong", "du", "yi",
                    "qi", "shu", "gang", "tiao", "none", "none", "none", "lai",
                    "shan", "mang", "yang", "ma", "miao", "si", "yuan", "hang",
                    "fei", "bei", "jie", "dong", "gao", "yao,miao", "xian",
                    "chu", "chun", "pa,ba", "shu", "hua", "xin", "chou,niu",
                    "zhu", "chou", "song", "ban", "song", "ji", "yue", "yun",
                    "gou", "ji", "mao", "pi", "bi", "wang", "ang", "fang",
                    "fen", "yi", "fu", "nan", "xi", "hu", "ya", "dou", "xun",
                    "zhen", "yao", "lin", "rui", "e", "mei", "zhao", "guo",
                    "zhi,qi", "zong,cong", "yun", "none", "dou", "shu", "zao",
                    "none", "li", "lu", "jian", "cheng", "song", "qiang",
                    "feng", "nan", "xiao", "xian", "ku", "ping", "tai", "xi",
                    "zhi", "guai", "xiao", "jia", "jia", "gou,ju", "bao,fu",
                    "mo", "yi", "ye", "sang", "shi", "nie", "bi", "tuo,duo",
                    "yi", "ling", "bing", "ni", "la", "he", "ban", "fan,bian",
                    "zhong", "dai", "ci", "yang", "fu", "bo,bai", "mou", "gan",
                    "qi", "ran", "rou", "mao", "zhao", "song", "zhe", "xia",
                    "you", "shen", "ju,gui", "tuo", "zuo,zha", "nan", "ning",
                    "yong", "di", "zhi", "zha", "cha,zha", "dan", "gu", "none",
                    "jiu", "ao", "fu,bi", "jian", "bo", "duo", "ke", "nai",
                    "zhu", "bi", "liu", "chai", "zha", "si", "zhu", "pei",
                    "shi", "guai", "cha,zha", "yao", "cheng", "jiu", "shi",
                    "zhi", "liu", "mei", "none", "rong", "zha,shan", "none",
                    "biao", "zhan", "zhi", "long", "dong", "lu", "none",
                    "li,yue", "lan", "yong", "shu", "xun", "shuan", "qi",
                    "zhen", "qi,xi", "li", "chi,yi", "xiang", "zhen", "li",
                    "su", "gua,kuo", "kan", "bing,ben", "ren", "xiao,jiao",
                    "bo,bai", "ren", "bing", "zi", "chou", "yi", "ci", "xu",
                    "zhu", "jian", "zui", "er", "er", "yu", "fa", "gong",
                    "kao", "lao", "zhan", "li", "none", "yang", "he,hu", "gen",
                    "zhi", "chi", "ge", "zai", "luan", "fa", "jie",
                    "heng,hang", "gui", "tao", "guang", "wei", "kuang", "ru",
                    "an", "an", "juan", "yi", "zhuo", "ku", "zhi", "qiong",
                    "tong", "sang", "sang", "huan", "jie,ju", "jiu", "xue",
                    "duo", "zhui", "yu", "zan", "none", "ying", "none", "none",
                    "zhan", "ya", "rao", "zhen", "dang", "qi", "qiao", "hua",
                    "gui,hui", "jiang", "zhuang", "xun", "suo", "suo", "zhen",
                    "bei", "ting", "kuo", "jing", "bo", "ben", "fu", "rui",
                    "tong", "jue", "xi", "lang", "liu", "feng", "qi", "wen",
                    "jun", "gan", "cu", "liang", "qiu", "ting", "you", "mei",
                    "bang", "long", "peng", "zhuang", "di", "xuan", "tu",
                    "zao", "ao", "gu", "bi", "di", "han", "zi", "zhi", "ren",
                    "bei", "geng", "jian", "huan", "wan", "nuo", "jia", "tiao",
                    "ji", "xiao", "lu:", "kuan", "shao,sao", "cen", "fen",
                    "song", "meng", "wu", "li", "li", "dou", "cen", "ying",
                    "suo", "ju", "ti", "xie", "kun", "zhuo", "shu", "chan",
                    "fan", "wei", "jing", "li", "bing", "none", "none", "tao",
                    "zhi", "lai", "lian", "jian", "zhuo", "ling", "li", "qi",
                    "bing", "lun", "cong", "qian", "mian", "qi", "qi", "cai",
                    "gun", "chan", "de", "fei", "pai", "bang", "pou,bang",
                    "hun", "zong", "cheng", "zao", "ji", "li", "peng", "yu",
                    "yu", "gu", "hun", "dong", "tang", "gang", "wang", "di",
                    "xi", "fan", "cheng", "zhan", "qi", "yuan", "yan", "yu",
                    "quan", "yi", "sen", "ren", "chui", "leng,ling", "qi,xi",
                    "zhuo", "fu", "ke", "lai", "zou", "zou", "zhao,zhuo",
                    "guan", "fen", "fen", "chen", "qiong", "nie", "wan", "guo",
                    "lu", "hao", "jie", "yi", "chou", "ju", "ju",
                    "cheng,sheng", "zuo", "liang", "qiang", "zhi", "zhui,chui",
                    "ya", "ju", "bei,pi", "jiao", "zhuo", "zi", "bin", "peng",
                    "ding", "chu", "shan", "none", "none", "jian", "gui", "xi",
                    "du", "qian", "none", "kui", "none", "luo", "zhi", "none",
                    "none", "none", "none", "peng", "shan", "none", "tuo",
                    "sen", "duo", "ye", "fu", "wei", "wei", "duan", "jia",
                    "zong", "jian", "yi", "shen,zhen", "xi", "yan", "yan",
                    "chuan", "zhan", "chun", "yu,ju", "he", "zha,cha", "wo",
                    "bian", "bi", "yao", "huo", "xu", "ruo", "yang", "la",
                    "yan", "ben", "hun", "kui", "jie", "kui", "si", "feng",
                    "xie", "tuo", "ji", "jian", "mu", "mao", "chu", "hu,ku",
                    "hu", "lian", "leng", "ting", "nan", "yu", "you", "mei",
                    "song", "xuan", "xuan", "ying", "zhen", "pian", "die",
                    "ji", "jie", "ye", "chu", "shun,dun", "yu", "cou", "wei",
                    "mei", "di", "ji", "jie", "kai,jie", "qiu", "ying", "rou",
                    "heng", "lou", "le,yue", "none", "gui", "pin", "none",
                    "gai", "tan", "lan", "yun", "yu", "chen", "lu:", "ju",
                    "none", "none", "none", "xie", "jia", "yi", "zhan", "fu",
                    "nuo", "mi", "lang", "rong", "gu", "jian", "ju", "ta",
                    "yao", "zhen", "bang", "sha", "yuan", "zi", "ming", "su",
                    "jia", "yao", "jie", "huang", "gan,han", "fei", "zha",
                    "qian", "ma", "sun", "yuan", "xie", "rong", "shi", "zhi",
                    "cui", "yun", "ting", "liu", "rong", "tang", "que", "zhai",
                    "si", "sheng", "ta", "ke", "xi", "gu", "qi", "kao", "gao",
                    "sun", "pan", "tao", "ge", "xun", "dian,zhen", "nou", "ji",
                    "shuo", "gou", "chui", "qiang", "cha", "qian", "huai",
                    "mei", "xu", "gang", "gao", "zhuo", "tuo", "qiao", "yang",
                    "dian", "jia", "jian,kan", "zui", "none", "long",
                    "bin,bing", "zhu", "none", "xi", "qi", "lian", "hui",
                    "yong", "qian", "guo", "gai", "gai", "tuan", "hua",
                    "qi,cu", "sen", "cui", "beng", "you", "hu", "jiang", "hu",
                    "huan", "kui", "yi", "yi", "gao", "kang", "gui", "gui",
                    "cao", "man", "jin", "di", "zhuang", "le,yue", "lang",
                    "chen", "cong,zong", "li", "xiu", "qing", "shuang", "fan",
                    "tong", "guan", "ji", "suo", "lei", "lu", "liang", "mi",
                    "lou", "chao", "su", "ke", "chu,shu", "tang", "biao", "lu",
                    "jiu", "shu", "zha", "shu", "zhang", "men", "mo,mu",
                    "niao", "yang", "tiao", "peng", "zhu", "sha", "xi", "quan",
                    "heng", "jian", "cong", "none", "none", "qiang", "none",
                    "ying", "er", "xin", "zhi", "qiao", "zui", "cong", "pu,po",
                    "shu", "hua", "kui", "zhen", "zun", "yue", "zhan", "xi",
                    "xun", "dian", "fa", "gan", "mo,mu", "wu", "qiao,cui",
                    "rao,nao", "lin", "liu", "qiao", "xian", "run", "fan",
                    "zhan", "tuo", "lao", "yun", "shun", "tui", "cheng",
                    "tang", "meng", "ju", "cheng", "su", "jue", "jue", "tan",
                    "hui", "ji", "nuo", "xiang", "tuo", "ning", "rui", "zhu",
                    "tong,chuang", "zeng", "fen", "qiong", "ran", "heng",
                    "cen", "gu,ku", "liu", "lao", "gao", "chu", "none", "none",
                    "none", "none", "ji", "dou", "none", "lu", "none", "none",
                    "yuan", "ta", "shu", "jiang", "tan", "lin", "nong", "yin",
                    "xi", "sui", "shan", "zui", "xuan", "cheng", "gan", "ju",
                    "zui", "yi", "qin", "pu", "yan,yin", "lei", "feng", "hui",
                    "dang", "ji", "sui", "bo", "bi", "ding", "chu", "zhua",
                    "gui,hui,kuai", "ji", "jia", "jia", "qing", "zhe", "jian",
                    "qiang", "dao", "yi", "biao", "song", "she", "lin",
                    "li,yue", "cha", "meng", "yin", "tao", "tai", "mian", "qi",
                    "none", "bin,bing", "huo", "ji", "qian", "mi,ni", "ning",
                    "yi", "gao", "jian,kan", "yin", "er", "qing", "yan", "qi",
                    "mi", "zhao", "gui,ju", "chun", "ji", "kui", "po", "deng",
                    "chu", "none", "mian", "you", "zhi", "guang", "qian",
                    "lei", "lei", "sa", "lu", "none", "cuan", "lu:", "mie",
                    "hui", "ou", "lu:", "zhi,jie", "gao", "du", "yuan",
                    "li,yue", "fei", "zhu", "sou", "lian", "none", "chu",
                    "none", "zhu", "lu", "yan", "li", "zhu", "chen", "jie",
                    "e", "su", "huai", "nie", "yu", "long", "lai", "none",
                    "xian", "none", "ju", "xiao", "ling", "ying", "jian",
                    "yin", "you", "ying", "xiang", "nong", "bo", "chan", "lan",
                    "ju", "shuang", "she", "wei", "cong", "quan", "qu", "none",
                    "none", "yu", "luo", "li", "zan", "luan", "dang", "jue",
                    "none", "lan", "lan", "zhu", "lei", "li,ji", "ba", "nang",
                    "yu", "ling", "none", "qian", "ci", "huan", "xin", "yu",
                    "yu", "qian", "ou", "xu", "chao", "chu", "qi", "kai", "yi",
                    "jue", "xi", "xu", "xia", "yu", "kuai", "lang", "kuan",
                    "shuo", "xi", "e^,ai", "yi,qi", "qi", "hu", "chi", "qin",
                    "kuan", "kan", "kuan", "kan", "chuan", "sha", "none",
                    "yin", "xin", "xie", "yu", "qian", "xiao", "yi", "ge",
                    "wu", "tan", "jin", "ou", "hu", "ti", "huan", "xu", "pen",
                    "xi", "xiao", "hu", "she,xi", "none", "lian", "chu", "yi",
                    "kan", "yu", "chuo", "huan", "zhi", "zheng", "ci", "bu",
                    "wu", "qi", "bu", "bu", "wai", "ju", "qian", "chi", "se",
                    "chi", "se", "zhong", "sui", "sui", "li", "cuo", "yu",
                    "li", "gui", "dai", "dai", "si", "jian", "zhe", "mo", "mo",
                    "yao", "mo", "cu", "yang", "tian", "sheng", "dai", "shang",
                    "xu", "xun", "shu", "can", "jue", "piao", "qia", "qiu",
                    "su", "qing", "yun", "lian", "yi", "fou", "zhi,shi", "ye",
                    "can", "hun", "dan", "ji", "ye", "none", "yun", "wen",
                    "chou,xiu", "bin", "ti", "jin", "shang", "yin", "diao",
                    "cu", "hui", "cuan", "yi", "dan", "du", "jiang", "lian",
                    "bin", "du", "jian", "jian", "shu", "ou", "duan", "zhu",
                    "yin,yan", "qing", "yi", "sha,shai", "ke,qiao",
                    "ke,qiao,que", "yao", "xun", "dian", "hui", "hui", "gu",
                    "que", "ji", "yi", "ou", "hui", "duan", "yi", "xiao", "wu",
                    "guan", "mu", "mei", "mei", "ai", "zuo", "du", "yu", "bi",
                    "bi", "bi", "pi", "pi", "bi", "chan", "mao", "none",
                    "none", "pi", "none", "jia", "zhan", "sai", "mu", "tuo",
                    "xun", "er", "rong", "xian", "ju", "mu", "hao", "qiu",
                    "dou", "none", "tan", "pei", "ju", "duo", "cui", "bi",
                    "san", "none", "mao", "sui", "shu", "yu", "tuo", "he",
                    "jian", "ta", "san", "lu:", "mu", "li", "tong", "rong",
                    "chang", "pu", "lu", "zhan", "sao", "zhan", "meng", "lu",
                    "qu", "die", "shi,zhi", "di", "min", "jue", "mang,meng",
                    "qi", "pie", "nai", "qi", "dao", "xian", "chuan", "fen",
                    "ri", "nei,nai", "none", "fu", "shen", "dong", "qing",
                    "qi", "yin", "xi", "hai", "yang", "an", "ya", "ke", "qing",
                    "ya", "dong", "dan", "lu:", "qing", "yang", "yun", "yun",
                    "shui", "shui", "zheng", "bing", "yong", "dang", "shui",
                    "le", "ni", "tun", "fan", "gui", "ting", "zhi", "qiu",
                    "bin", "ze", "mian", "cuan", "hui", "diao", "han", "cha",
                    "zhuo", "chuan", "wan", "fan", "dai", "xi", "tuo", "mang",
                    "qiu", "qi", "shan", "pai", "han", "qian", "wu", "wu",
                    "xun", "si", "ru", "gong,hong", "jiang", "chi", "wu",
                    "none", "none", "tang,shang", "zhi", "chi", "qian", "mi",
                    "gu", "wang", "qing", "jing", "rui", "jun", "hong", "tai",
                    "quan", "ji", "bian", "bian", "gan", "wen", "zhong",
                    "fang", "xiong", "jue", "hu", "none", "qi", "fen", "xu",
                    "xu", "qin,shen", "yi", "wo", "yun", "yuan", "hang", "yan",
                    "shen,chen", "chen", "dan", "you", "dun,zhuan", "hu",
                    "huo", "qi", "mu", "rou", "mei,mo", "ta,da", "mian", "wu",
                    "chong", "tian", "bi", "sha", "zhi", "pei", "pan", "zhui",
                    "za", "gou", "liu", "mei,mo", "ze", "feng", "ou", "li",
                    "lun", "cang", "feng", "wei", "hu", "mo", "mei", "shu",
                    "ju", "zan", "tuo", "tuo", "duo", "he", "li", "mi", "yi",
                    "fu", "fei", "you", "tian", "zhi", "zhao", "gu", "zhan",
                    "yan", "si", "kuang", "jiong", "ju", "xie", "qiu", "yi",
                    "jia", "zhong", "quan", "bo,po", "hui", "mi,bi", "ben",
                    "zhuo", "chu", "le", "you", "gu", "hong", "gan", "fa",
                    "mao", "si", "hu", "ping", "ci", "fan", "zhi", "su",
                    "ning", "cheng", "ling", "pao", "bo,po", "qi,xie", "si",
                    "ni", "ju", "yue", "zhu", "sheng", "lei", "xuan", "xue",
                    "fu", "pan", "min", "tai", "yang", "ji", "yong", "guan",
                    "beng", "xue", "long,shuang", "lu", "dan", "luo,po", "xie",
                    "po", "ze", "jing", "yin", "zhou", "jie", "yi", "hui",
                    "hui", "zui", "cheng", "yin", "wei", "hou", "jian", "yang",
                    "lie", "si", "ji", "er", "xing", "fu", "sa", "zi", "zhi",
                    "yin", "wu", "xi,xian", "kao", "zhu", "jiang", "luo",
                    "none", "an", "dong", "yi", "mou", "lei", "yi", "mi",
                    "quan", "jin", "po", "wei", "xiao", "xie", "hong", "xu",
                    "su", "kuang", "tao", "qie,jie", "ju", "er", "zhou", "ru",
                    "ping", "xun", "xiong", "zhi", "guang,huang", "huan",
                    "ming", "huo", "wa", "qia,xia", "pai", "wu", "qu", "liu",
                    "yi", "jia", "jing", "qian,jian", "jiang", "jiao", "zhen",
                    "shi", "zhuo", "ce", "none", "hui,kuai", "ji", "liu",
                    "chan", "hun", "hu,xu", "nong", "xun", "jin", "lie", "qiu",
                    "wei", "zhe", "jun,xun", "han", "bang", "mang", "zhuo",
                    "you", "xi", "bo", "dou", "huan,wan", "hong", "yi", "pu",
                    "ying", "lan", "hao", "lang", "han", "li", "geng", "fu",
                    "wu", "li", "chun", "feng", "yi", "yu", "tong", "lao",
                    "hai", "jin", "jia", "chong", "weng", "mei", "sui",
                    "cheng", "pei", "xian", "shen", "tu", "kun", "pin", "nie",
                    "han", "jing", "xiao", "she", "nian", "tu", "yong,chong",
                    "xiao", "xian", "ting", "e", "su", "tun", "juan", "cen",
                    "ti", "li", "shui", "si", "lei", "shui", "tao", "du",
                    "lao", "lai", "lian", "wei", "wo,guo", "yun", "huan", "di",
                    "none", "run", "jian", "zhang", "se", "fu", "guan", "xing",
                    "shou", "shuan", "ya", "chuo", "zhang", "ye,yi", "kong",
                    "wan", "han", "tuo", "dong", "he,hao", "wo", "ju", "gan",
                    "liang", "hun", "ta", "zhuo", "dian", "qie", "de", "juan",
                    "zi", "xi", "xiao,yao", "qi", "gu", "guo", "han", "lin",
                    "tang", "zhou", "peng", "hao", "chang", "shu", "qi",
                    "fang", "chi", "lu", "nao", "ju", "tao", "cong", "lei",
                    "zhi", "peng", "fei", "song", "tian", "pi", "dan", "yu",
                    "ni", "yu", "lu", "gan", "mi", "jing", "ling", "lun",
                    "yin", "cui", "qu", "huai", "yu", "nian", "shen",
                    "piao,hu", "chun", "hu", "yuan", "lai", "hun", "qing",
                    "yan", "qian,jian", "tian", "miao", "zhi", "yin", "mi",
                    "ben", "yuan", "wen", "re", "fei", "qing", "yuan", "ke",
                    "ji", "she", "yuan", "se", "lu", "zi", "du", "none",
                    "jian", "mian,sheng", "pi", "xi", "yu", "yuan", "shen",
                    "shen", "rou", "huan", "zhu", "jian", "nuan", "yu", "qiu",
                    "ting", "qu", "du", "feng", "zha", "bo", "wo", "wo,guo",
                    "di", "wei", "wen", "ru", "xie", "ce", "wei", "ge", "gang",
                    "yan", "hong", "xuan", "mi", "ke", "mao", "ying", "yan",
                    "you", "hong", "miao", "xing", "mei", "zai", "hun", "nai",
                    "kui", "shi", "e", "pai", "mei", "lian", "qi", "qi", "mei",
                    "tian", "cou", "wei", "can", "tuan", "mian", "xu", "mo",
                    "xu", "ji", "pen", "jian", "jian", "hu", "feng", "xiang",
                    "yi", "yin", "zhan", "shi", "jie", "zhen", "huang", "tan",
                    "yu", "bi", "min", "shi", "tu", "sheng", "yong,chong",
                    "ju", "zhong", "none", "qiu,jia,jiao,jiu", "jiao", "none",
                    "yin,yan", "tang,shang", "long", "huo", "yuan", "nan",
                    "ban", "you", "quan", "chui", "liang", "chan", "yan",
                    "chun", "nie", "zi", "wan", "shi", "man", "ying", "la",
                    "kui,hui", "none", "jian", "xu", "lou", "gui", "gai",
                    "none", "none", "po", "jin", "gui", "tang", "yuan", "suo",
                    "yuan", "lian", "yao", "meng", "zhun", "sheng", "ke",
                    "tai", "ta", "wa", "liu", "gou", "sao", "ming", "zha",
                    "shi", "yi", "lun", "ma", "pu", "wei", "li", "cai", "wu",
                    "xi,qi", "wen", "qiang", "ce", "shi", "su", "yi",
                    "zhen,qin", "sou", "yun", "xiu", "yin", "rong", "hun",
                    "su", "su", "ni,niao", "ta", "shi", "ru", "wei", "pan",
                    "chu", "chu", "pang", "weng", "cang", "mie", "he", "dian",
                    "hao", "huang", "xi", "zi", "di", "zhi", "ying,xing"
            };
        }
    }
}
