
package cn.com.nd.momo.api.util;

/**
 * 多音节，从0x8F9F到0x9FA5
 * 
 * @author chenjp
 */
public class MultiPinYin5 {
    public static String[] pinyinArray = null;

    private MultiPinYin5() {
    };

    static {
        if (null == pinyinArray) {
            pinyinArray = new String[] {
                    "pi,bi", "zui", "bian", "la", "la", "ci",
                    "xue", "ban", "bian", "bian", "bian", "none", "bian",
                    "ban", "ci", "bian", "bian", "chen", "ru", "nong", "nong",
                    "zhen", "chuo", "chuo", "none", "reng", "bian", "bian",
                    "none", "none", "liao", "da", "chan", "gan", "qian", "yu",
                    "yu", "qi", "xun", "yi", "guo", "mai", "qi", "za", "wang",
                    "none", "zhun", "ying", "ti", "yun", "jin", "hang", "ya",
                    "fan", "wu", "ta", "e", "hai,huan", "zhei", "none", "jin",
                    "yuan", "wei", "lian", "chi", "che", "ni", "tiao", "zhi",
                    "yi", "jiong", "jia", "chen", "dai", "er", "di", "po,pai",
                    "wang", "die", "ze", "tao", "shu", "tuo", "none", "jing",
                    "hui", "tong", "you", "mi", "beng", "ji", "nai", "yi",
                    "jie", "zhui", "lie", "xun", "tui", "song", "shi,kuo",
                    "tao", "pang", "hou", "ni", "dun", "jiong", "xuan", "xun",
                    "bu", "you", "xiao", "qiu", "tou", "zhu", "qiu", "di",
                    "di", "tu", "jing", "ti", "dou", "yi", "zhe,zhei", "tong",
                    "guang", "wu", "shi", "cheng", "su", "zao", "qun", "feng",
                    "lian", "suo", "hui", "li", "none", "zui", "ben", "cuo",
                    "jue", "beng", "huan", "dai", "lu", "you", "zhou", "jin",
                    "yu", "chuo", "kui", "wei", "ti", "yi", "da", "yuan",
                    "luo", "bi", "nuo", "yu", "dang", "sui", "dun", "sui",
                    "yan", "chuan", "chi", "ti", "yu", "shi", "zhen", "you",
                    "yun", "e", "bian,pian", "guo", "e", "xia", "huang", "qiu",
                    "dao", "da", "wei", "none", "yi,wei", "gou", "yao", "chu",
                    "liu", "xun", "ta", "di", "chi", "yuan", "su", "ta",
                    "qian", "none", "yao", "guan", "zhang", "ao", "shi,kuo",
                    "ce", "su", "su", "zao", "zhe", "dun", "zhi", "lou", "chi",
                    "cuo", "lin", "zun", "rao", "qian", "xuan", "yu", "yi,wei",
                    "wu", "liao", "ju", "shi", "bi", "yao", "mai", "xie",
                    "sui", "huan,hai,xuan", "zhan", "deng", "er", "miao",
                    "bian", "bian", "la", "li", "yuan", "you", "luo", "li",
                    "yi", "ting", "deng", "qi", "yong", "shan", "han", "yu",
                    "mang", "ru", "qiong", "none", "kuang", "fu", "kang",
                    "bin", "fang", "xing", "nei,na", "none", "shen", "bang",
                    "yuan", "cun", "huo", "xie,ye", "bang", "wu", "ju", "you",
                    "han", "tai", "qiu", "bi", "pi", "bing", "shao", "bei",
                    "wa", "di", "zou", "ye", "lin", "kuang", "gui", "zhu",
                    "shi", "ku", "yu", "gai", "he", "qie", "zhi", "ji",
                    "xun,huan", "hou", "xing", "jiao", "xi", "gui", "nuo",
                    "lang", "jia", "kuai", "zheng", "lang", "yun", "yan",
                    "cheng", "dou", "xi", "lu:", "fu", "wu", "fu", "gao",
                    "hao", "lang", "jia", "geng", "jun", "ying", "bo", "xi",
                    "bei", "li", "yun", "bu", "xiao", "qi", "pi", "qing",
                    "guo", "none", "tan", "zou", "ping", "lai", "ni", "chen",
                    "you", "bu", "xiang", "dan", "ju", "yong", "qiao", "yi",
                    "dou,du", "yan", "mei", "ruo", "bei", "e", "yu", "juan",
                    "yu", "yun", "hou", "kui", "xiang", "xiang", "sou", "tang",
                    "ming", "xi", "ru", "chu", "zi", "zou", "ju", "wu",
                    "xiang", "yun", "hao", "yong", "bi", "mao", "chao", "fu",
                    "liao", "yin", "zhuan", "hu", "qiao", "yan", "zhang",
                    "fan", "wu", "xu", "deng", "bi", "xin", "bi", "ceng",
                    "wei", "zheng", "mao", "shan", "lin", "po", "dan", "meng",
                    "ye", "cao", "kuai", "feng", "meng", "zou", "kuang",
                    "lian", "zan", "chan", "you", "qi", "yan", "chan", "cuo",
                    "ling", "huan", "xi", "feng", "zan", "li", "you", "ding",
                    "qiu", "zhuo", "pei", "zhou", "yi", "gan", "yu", "jiu",
                    "yan", "zui", "mao", "dan,zhen", "xu", "tou", "zhen",
                    "fen", "none", "none", "yun", "tai", "tian", "qia", "tuo",
                    "zuo,cu", "han", "gu", "su", "fa,po", "chou", "dai",
                    "ming", "lao,luo", "chuo", "chou", "you", "tong", "zhi",
                    "xian", "jiang", "cheng", "yin", "tu", "jiao,xiao", "mei",
                    "ku", "suan", "lei", "pu", "zui", "hai", "yan", "shi,shai",
                    "niang", "wei", "lu", "lan", "yan", "tao", "pei", "zhan",
                    "chun", "tan", "zui", "chuo", "cu", "kun", "ti", "xian",
                    "du", "hu", "xu", "xing", "tan", "qiu", "chun", "yun",
                    "fa,po", "ke", "sou", "mi", "quan", "chou", "cuo", "yun",
                    "yong", "ang", "zha", "hai", "tang", "jiang", "piao",
                    "lao", "yu", "li", "zao", "lao", "yi", "jiang", "bu",
                    "jiao", "xi", "tan", "fa,po", "nong", "yi", "li", "ju",
                    "yan", "yi", "niang", "ru", "xun", "chou", "yan", "ling",
                    "mi", "mi", "niang", "xin", "jiao", "shi", "mi", "yan",
                    "bian", "cai", "shi", "you", "shi", "shi", "li",
                    "zhong,chong", "ye", "liang", "li,xi", "jin", "jin", "ga",
                    "yi", "liao", "dao", "zhao", "ding", "li", "qiu", "he",
                    "fu", "zhen", "zhi", "ba", "luan", "fu", "nai", "diao",
                    "shan", "qiao", "kou", "chuan", "zi", "fan", "yu", "hua",
                    "han", "gong,gang", "qi", "mang", "jian", "di", "si", "xi",
                    "yi", "chai", "ta,tuo", "tu", "xi", "nu:", "qian", "none",
                    "jian", "pi", "ye", "yin", "ba,pa", "fang", "chen", "jian",
                    "tou", "yue", "yan", "fu", "bu", "na", "xin", "e", "jue",
                    "dun", "gou", "yin", "qian", "ban", "ji", "ren", "chao",
                    "niu", "fen", "yun", "yi", "qin", "pi", "guo", "hong",
                    "yin", "jun", "shi", "yi", "zhong", "nie", "gai", "ri",
                    "huo", "tai", "kang", "none", "lu", "none", "none", "duo",
                    "zi", "ni", "tu", "shi", "min", "gu", "ke", "ling", "bing",
                    "yi", "gu", "ba", "pi", "yu", "si", "zuo", "bu", "you",
                    "dian,tian", "jia", "zhen", "shi", "shi", "tie", "ju",
                    "zhan", "ta,tuo", "she,tuo,ta", "xuan", "zhao", "bao",
                    "he", "bi", "sheng", "chu", "shi", "bo", "zhu", "chi",
                    "za", "po", "tong", "qian", "fu", "zhai", "liu,mao",
                    "qian,yan", "fu", "li", "yue", "pi", "yang", "ban", "bo",
                    "jie", "gou", "shu", "zheng", "mu", "ni", "xi", "di",
                    "jia", "mu", "tan", "shen", "yi", "si", "kuang", "ka",
                    "bei", "jian", "tong", "xing", "hong", "jiao", "chi", "er",
                    "ge", "bing", "shi", "mou", "jia,ha", "yin", "jun", "zhou",
                    "chong", "shang", "tong", "mo", "lei", "ji", "yu", "xu",
                    "ren", "cun", "zhi", "qiong", "shan", "chi", "xian",
                    "xing", "quan", "pi", "yi", "zhu", "hou", "ming", "kua",
                    "yao,diao,tiao", "xian", "xian", "xiu", "jun", "cha",
                    "lao", "ji", "yong", "ru", "mi", "yi", "yin", "guang",
                    "an", "diu", "you", "se", "kao", "qian", "luan", "none",
                    "ai", "diao", "han", "rui", "shi", "keng", "qiu", "xiao",
                    "zhe", "xiu", "zang", "ti", "cuo", "gua", "gong", "zhong",
                    "dou", "lu:", "mei", "lang", "wan", "xin", "yun", "bei",
                    "wu", "su", "yu", "chan", "ting,ding", "bo", "han", "jia",
                    "hong", "cuan", "feng", "chan", "wan", "zhi", "si", "xuan",
                    "wu", "wu", "tiao", "gong", "zhuo", "lu:e", "xing", "qin",
                    "shen", "han", "none", "ye", "chu", "zeng", "ju", "xian",
                    "e", "mang", "pu", "li", "shi", "rui", "cheng", "gao",
                    "li", "te", "none", "zhu", "none", "tu", "liu", "zui",
                    "ju", "chang", "yuan", "jian", "gang", "diao", "tao",
                    "chang", "lun", "guo", "ling", "bei", "lu", "li",
                    "qing,qiang", "pei", "juan", "min", "zui", "peng", "an",
                    "pi", "xian", "ya", "zhui", "lei", "a,e", "kong", "ta",
                    "kun", "du", "wei", "chui", "zi", "zheng", "ben", "nie",
                    "cong", "chun", "tan", "ding", "qi", "qian", "zhuo", "qi",
                    "yu", "jin", "guan", "mao", "chang", "dian", "xi", "lian",
                    "tao", "gu", "cuo", "shu", "zhen", "lu", "meng", "lu",
                    "hua", "biao", "ga", "lai", "ken", "zhui", "none", "nai",
                    "wan", "zan", "none", "de", "xian", "none", "huo", "liang",
                    "none", "men", "kai", "ying", "di", "lian", "guo", "xian",
                    "du", "tu", "wei", "cong", "fu", "rou", "ji", "e", "rou",
                    "chen", "ti", "zha", "hong", "yang", "duan", "xia", "yu",
                    "keng", "xing", "huang", "wei", "fu", "zhao", "cha", "qie",
                    "she", "hong", "kui", "nuo", "mou", "qiao", "qiao", "hou",
                    "zhen", "huo", "huan", "ye", "min", "jian", "duan", "jian",
                    "si", "kui", "hu", "xuan", "zang,zhe", "jie", "zhen",
                    "bian", "zhong", "zi", "xiu", "ye", "mei", "pai", "ai",
                    "jie", "none", "mei", "cha", "ta", "bang", "xia", "lian",
                    "suo", "xi", "liu", "zu", "ye", "nou", "weng", "rong",
                    "tang", "suo", "qiang", "ge", "shuo", "chui", "bo", "pan",
                    "ta", "bi", "sang", "gang", "zi", "wu", "ying", "huang",
                    "tiao", "liu", "kai", "sun", "sha", "sou", "wan",
                    "hao,gao", "zhen", "zhen", "luo", "yi", "yuan", "tang",
                    "nie", "xi", "jia", "ge", "ma", "juan", "rong", "none",
                    "suo", "none", "none", "none", "na", "lu", "suo", "kou",
                    "zu,cu", "tuan", "xiu", "guan", "xuan", "lian", "shou",
                    "ao", "man", "mo", "luo", "bi", "wei", "liu", "di", "qiao",
                    "huo", "yin", "lu", "ao", "keng", "qiang", "cui", "qi",
                    "chang", "tang", "man", "yong", "chan", "feng", "jing",
                    "biao", "shu", "lou", "xiu", "cong", "long", "zan", "jian",
                    "cao", "li", "xia", "xi", "kang", "none", "beng", "none",
                    "none", "zheng", "lu", "hua", "ji", "pu", "hui", "qiang",
                    "po", "lin", "suo", "xiu", "san", "cheng", "kui", "san",
                    "liu", "nao", "huang", "pie", "sui", "fan", "qiao",
                    "chuan", "yang", "tang", "xiang", "jue", "jiao", "zun",
                    "liao", "jie", "lao", "dui,dun", "tan,chan,xin", "zan",
                    "ji", "jian", "zhong", "deng", "lou,lue", "ying", "dui",
                    "jue", "nou", "ti", "pu", "tie", "none", "none", "ding",
                    "shan", "kai", "jian", "fei", "sui", "lu", "juan", "hui",
                    "yu", "lian", "zhuo", "qiao", "qian", "zhuo", "lei", "bi",
                    "tie", "huan", "ye", "duo", "guo", "dang,cheng", "ju",
                    "fen", "da", "bei", "yi", "ai", "dang,zheng", "xun",
                    "diao,yao", "zhu", "heng", "zhui", "ji", "nie", "ta",
                    "huo", "qing", "bin", "ying", "kui", "ning", "xu", "jian",
                    "jian", "qiang", "cha", "zhi", "mie", "li", "lei", "ji",
                    "zuan", "kuang", "shang", "peng", "la", "du", "shuo",
                    "chuo", "lu:", "biao", "bao", "lu", "none", "none", "long",
                    "e", "lu", "xin", "jian", "lan", "bo", "jian", "yao,yue",
                    "chan", "xiang", "jian", "xi", "guan", "cang", "nie",
                    "lei", "cuan", "qu", "pan", "luo", "zuan", "luan",
                    "zao,zuo", "nie", "jue", "tang", "shu", "lan", "jin", "ga",
                    "yi", "zhen", "ding", "zhao", "po", "liao", "tu", "qian",
                    "chuan", "shan", "sa", "fan", "diao", "men", "nu:", "yang",
                    "chai", "xing", "gai", "bu", "tai", "ju", "dun", "chao",
                    "zhong", "na", "bei", "gang", "ban", "qian", "yao,yue",
                    "qin", "jun", "wu", "gou", "kang", "fang", "huo", "tou",
                    "niu", "ba,pa", "yu", "qian", "zheng", "qian", "gu", "bo",
                    "ke", "po", "bu", "bo", "yue", "zuan", "mu", "tan", "jia",
                    "dian,tian", "you", "tie", "bo", "ling", "shuo",
                    "qian,yan", "mao", "bao", "shi", "xuan", "tuo,she,ta",
                    "bi", "ni", "pi", "duo", "xing", "kao", "lao", "er",
                    "mang", "ya", "you", "cheng", "jia", "ye", "nao", "zhi",
                    "dang,cheng", "tong", "lu:", "diao", "yin", "kai", "zha",
                    "zhu", "xian", "ting,ding", "diu", "xian", "hua", "quan",
                    "sha", "ha", "yao,diao,tiao", "ge", "ming", "zheng", "se",
                    "jiao", "yi", "chan", "chong", "tang", "an", "yin", "ru",
                    "zhu", "lao", "pu", "wu", "lai", "te", "lian", "keng",
                    "xiao", "suo", "li", "zeng", "chu", "guo", "gao", "e",
                    "xiu", "cuo", "lu:e", "feng", "xin", "liu", "kai", "jian",
                    "rui", "ti", "lang", "qin", "ju", "a", "qing,qiang",
                    "zhe,zang", "nuo", "cuo", "mao", "ben", "qi", "de", "ke",
                    "kun", "chang", "xi", "gu", "luo", "chui", "zhui", "jin",
                    "zhi", "xian", "juan", "huo", "pei", "tan", "ding", "jian",
                    "ju", "meng", "zi", "qie", "ying", "kai", "qiang", "si",
                    "e", "cha", "qiao", "zhong", "duan", "sou", "huang",
                    "huan", "ai", "du", "mei", "lou", "zi", "fei", "mei", "mo",
                    "zhen", "bo", "ge", "nie", "tang", "juan", "nie", "na",
                    "liu", "hao,gao", "bang", "yi", "jia", "bin", "rong",
                    "biao", "tang", "man", "luo", "beng", "yong", "jing", "di",
                    "zu", "xuan", "liu", "chan,xin,tan", "jue", "liao", "pu",
                    "lu", "dun,dui", "lan", "pu", "cuan", "qiang", "deng",
                    "huo", "lei", "huan", "zhuo", "lian", "yi", "cha", "biao",
                    "la", "chan", "xiang", "chang,zhang", "chang,zhang", "jiu",
                    "ao", "die", "qu", "liao", "mi", "zhang,chang", "men",
                    "ma", "shuan", "shan", "huo", "men", "yan", "bi", "han",
                    "bi", "none", "kai", "kang", "beng", "hong", "run", "san",
                    "xian", "xian", "jian", "min", "xia", "min", "dou", "zha",
                    "nao", "none", "peng", "ke", "ling", "bian", "bi", "run",
                    "he", "guan", "ge", "he,ge", "fa", "chu", "hong", "gui",
                    "min", "none", "kun", "lang", "lu:", "ting", "sha", "yan",
                    "yue", "yue", "chan", "qu", "lin", "chang", "shai", "kun",
                    "yan", "min,wen", "yan", "e,yan", "hun", "yu", "wen",
                    "xiang", "none", "xiang", "qu", "yao", "wen", "ban", "an",
                    "wei", "yin", "kuo", "que", "lan", "du,she", "none",
                    "none", "tian", "nie", "da,ta", "kai", "he", "que",
                    "chuang", "guan", "dou", "qi", "kui", "tang", "guan",
                    "piao", "kan,han", "xi", "hui", "chan", "pi,bi", "dang",
                    "huan", "ta", "wen", "none", "men", "shuan", "shan", "yan",
                    "han", "bi", "wen", "chuang", "run", "wei", "xian", "hong",
                    "jian", "min", "kang", "men", "zha", "nao", "gui", "wen",
                    "ta", "min", "lu:", "kai", "fa", "ge", "he", "kun", "jiu",
                    "yue", "lang", "du,she", "yu", "yan", "chang", "xi", "wen",
                    "hun", "yan", "yan,e", "chan", "lan", "qu", "hui", "kuo",
                    "que", "he", "tian", "da,ta", "que", "kan,han", "huan",
                    "fu", "fu,yi", "le", "dui", "xin,shen", "qian", "wu", "yi",
                    "tuo", "yin", "yang", "dou", "e", "sheng", "ban", "pei",
                    "keng", "yun", "ruan", "zhi", "pi", "jing", "fang", "yang",
                    "yin", "zhen", "jie", "cheng", "e", "qu", "di", "zu",
                    "zuo", "dian,yan", "ling", "a,e", "tuo", "tuo",
                    "po,bei,pi", "bing", "fu", "ji", "lu,liu", "long", "chen",
                    "xing", "duo", "lou", "mo", "jiang,xiang", "shu", "duo",
                    "xian", "er", "gui", "wu", "gai", "shan", "jun", "qiao",
                    "xing", "chun", "fu", "bi", "shan", "shan,xia", "sheng",
                    "zhi", "pu", "dou", "yuan", "zhen", "chu", "xian", "zhi",
                    "nie", "yun", "xian", "pei", "pei", "zou", "yi", "dui",
                    "lun", "yin", "ju", "chui", "chen", "pi", "ling",
                    "tao,yao", "xian", "lu,liu", "none", "xian", "yin", "zhu",
                    "yang", "reng", "shan", "chong", "yan", "yin", "yu", "ti",
                    "yu", "long", "wei", "wei", "nie", "dui", "sui", "an",
                    "huang", "jie", "sui", "yin", "gai", "yan", "hui", "ge",
                    "yun", "wu", "wei,kui", "ai", "xi", "tang", "ji", "zhang",
                    "dao", "ao", "xi", "yin", "sa", "rao", "lin", "tui",
                    "deng", "pi", "sui", "sui", "yu", "xian", "fen", "ni",
                    "er", "ji", "dao", "xi", "yin", "zhi", "hui", "long", "xi",
                    "li", "li", "li", "zhui,cui", "he", "zhi", "sun,zhun",
                    "juan,jun", "nan", "yi", "que,qiao", "yan", "qin", "ya",
                    "xiong", "ya", "ji", "gu", "huan", "zhi", "gou",
                    "jun,juan", "ci", "yong", "ju", "chu", "hu", "za", "luo",
                    "yu", "chou", "diao", "sui", "han", "huo", "shuang",
                    "guan", "chu", "za", "yong", "ji", "sui", "chou", "liu",
                    "li", "nan", "xue", "za", "ji", "ji", "yu", "yu", "xue",
                    "na", "fou", "se", "mu", "wen", "fen", "pang", "yun", "li",
                    "li", "yang", "ling", "lei", "an", "bao", "meng", "dian",
                    "dang", "hang,yu", "wu", "zhao", "xu", "ji", "mu", "chen",
                    "xiao", "zha", "ting", "zhen", "pei", "mei", "ling", "qi",
                    "chou", "huo", "sha", "fei", "weng", "zhan", "ying", "ni",
                    "chou", "tun", "lin", "none", "dong", "ying,ji", "wu",
                    "ling", "shuang", "ling", "xia", "hong", "yin", "mai",
                    "mo", "yun", "liu", "meng", "bin", "wu", "wei", "kuo",
                    "yin", "xi", "yi", "ai", "dan", "deng", "xian,san", "yu",
                    "lu,lou", "long", "dai", "ji", "pang", "yang", "ba", "pi",
                    "wei", "none", "xi", "ji", "mai", "meng", "meng", "lei",
                    "li", "huo,sui", "ai", "fei", "dai", "long", "ling", "ai",
                    "feng", "li", "bao", "none", "he", "he", "bing", "qing",
                    "qing", "jing,liang", "qi", "zhen", "jing", "cheng",
                    "qing", "jing", "jing,liang", "dian", "jing", "tian",
                    "fei", "fei", "kao", "mi", "mian", "mian", "pao", "ye",
                    "tian,mian", "hui", "ye", "ge,ji", "ding", "ren", "jian",
                    "ren", "di", "du", "wu", "ren", "qin", "jin", "xue", "niu",
                    "ba", "yin", "sa", "ren", "mo", "zu", "da", "ban", "yi",
                    "yao", "tao", "bei,tuo", "jia", "hong", "pao", "yang",
                    "mo", "yin", "jia", "tao", "ji", "xie", "an", "an", "hen",
                    "gong", "gong", "da", "qiao", "ting", "man,wan", "ying",
                    "sui", "tiao", "qiao,shao", "xuan", "kong", "beng", "ta",
                    "zhang", "bing", "kuo", "ju", "la", "xie", "rou", "bang",
                    "yi,eng", "qiu", "qiu", "he", "xiao", "mu", "ju", "jian",
                    "bian", "di", "jian", "none", "tao", "gou", "ta", "bei",
                    "xie", "pan", "ge", "bi", "kuo,kui", "tang", "lou", "gui",
                    "qiao", "xue", "ji", "jian", "jiang", "chan", "da", "huo",
                    "xian", "qian", "du", "wa", "jian", "lan", "wei", "ren",
                    "fu", "mei", "juan", "ge", "wei", "qiao", "han", "chang",
                    "none", "rou", "xun", "she", "wei", "ge", "bei", "tao",
                    "gou", "yun", "gao", "bi", "wei", "hui", "shu", "wa", "du",
                    "wei", "ren", "fu", "han", "wei", "yun", "tao", "jiu",
                    "jiu", "xian", "xie", "xian", "ji", "yin", "za", "yun",
                    "shao", "luo", "peng", "huang", "ying", "yun", "peng",
                    "yin,an", "yin", "xiang", "hu", "ye", "ding", "qing",
                    "pan", "xiang", "shun", "han", "xu", "yi", "xu", "gu",
                    "song", "kui", "qi", "hang", "yu", "wan", "ban", "dun",
                    "di", "dan", "pan", "po", "ling", "cheng", "jing,geng",
                    "lei", "he,han", "qiao", "e", "e", "wei", "jie,xie", "gua",
                    "shen", "yi", "yi", "ke", "dui", "pian", "ping", "lei",
                    "fu", "jia", "tou", "hui", "kui", "jia", "le", "ting",
                    "cheng", "ying", "jun", "hu", "han", "jing,geng", "tui",
                    "tui", "pin", "lai", "tui", "zi", "zi", "chui", "ding",
                    "lai", "yan", "han", "qian", "ke", "cui", "jiong", "qin",
                    "yi", "sai", "ti", "e", "e", "yan", "hun", "kan", "yong",
                    "zhuan", "yan", "xian", "xin", "yi", "yuan", "sang",
                    "dian", "dian", "jiang", "ku", "lei", "liao", "piao", "yi",
                    "man", "qi", "yao", "hao", "qiao", "gu", "xun", "qian",
                    "hui", "zhan,chan", "ru", "hong", "bin", "xian", "pin",
                    "lu", "lan", "nie", "quan", "ye", "ding", "qing", "han",
                    "xiang", "shun", "xu", "xu", "wan", "gu", "dun", "qi",
                    "ban", "song", "hang", "yu", "lu", "ling", "po",
                    "jing,geng", "jie,xie", "jia", "ting", "he,ge", "ying",
                    "jiong", "ke", "yi", "pin", "hui", "tui", "han", "ying",
                    "ying", "ke", "ti", "yong", "e", "zhuan", "yan", "e",
                    "nie", "man", "dian", "sang", "hao", "lei", "zhan,chan",
                    "ru", "pin", "quan", "feng", "biao", "none", "fu", "xia",
                    "zhan", "biao", "sa", "fa", "tai", "lie", "gua", "xuan",
                    "shao", "ju", "biao", "si", "wei", "yang", "yao", "sou",
                    "kai", "sao", "fan", "liu", "xi", "liao", "piao", "piao",
                    "liu", "biao", "biao", "biao", "liao", "none", "se",
                    "feng", "biao", "feng", "yang", "zhan", "biao", "sa", "ju",
                    "si", "sou", "yao", "liu", "piao", "biao", "biao", "fei",
                    "fan", "fei", "fei", "shi,si,yi", "shi,si", "can", "ji",
                    "ding", "si", "tuo", "jian", "sun", "xiang", "tun", "ren",
                    "yu", "juan", "chi", "yin", "fan", "fan", "sun", "yin",
                    "zhu", "yi", "zhai", "bi", "jie", "tao", "liu", "ci",
                    "tie", "si", "bao", "shi", "duo", "hai", "ren", "tian",
                    "jiao", "jia", "bing", "yao", "tong", "ci", "xiang",
                    "yang", "yang", "er", "yan", "le", "yi", "can", "bo",
                    "nei", "e", "bu", "jun", "dou", "su", "yu", "shi", "yao",
                    "hun", "guo", "shi", "jian", "zhui", "bing", "xian", "bu",
                    "ye", "tan", "fei", "zhang", "wei", "guan", "e", "nuan",
                    "hun", "hu", "huang", "tie", "hui", "jian", "hou", "he",
                    "xing,tang", "fen", "wei", "gu", "cha", "song",
                    "tang,xing", "bo", "gao", "xi", "kui", "liu", "sou", "tao",
                    "ye", "yun", "mo", "tang", "man", "bi", "yu", "xiu", "jin",
                    "san", "kui", "zhuan", "shan", "chi", "dan", "yi", "ji",
                    "rao", "cheng", "yong", "tao", "hui", "xiang", "zhan",
                    "fen", "hai", "meng", "yan", "mo", "chan", "xiang", "luo",
                    "zuan,zan", "nang", "shi,si", "ding", "ji", "tuo",
                    "xing,tang", "tun", "xi", "ren", "yu", "chi", "fan", "yin",
                    "jian", "shi", "bao", "si", "duo", "yi", "er", "rao",
                    "xiang", "he", "le", "jiao", "xi", "bing", "bo", "dou",
                    "e", "yu", "nei", "jun", "guo", "hun", "xian", "guan",
                    "cha", "kui", "gu", "sou", "chan", "ye", "mo", "bo", "liu",
                    "xiu", "jin", "man", "san", "zhuan", "nang", "shou", "kui",
                    "guo", "xiang", "fen", "ba", "ni", "bi", "bo", "tu", "han",
                    "fei", "jian", "yan", "ai", "fu", "xian", "wen",
                    "xin,xing", "fen", "bin", "xing", "ma", "yu", "feng,ping",
                    "han", "di", "tuo,duo", "tuo", "chi", "xun", "zhu", "zhi",
                    "pei", "xin", "ri", "sa", "yin", "wen", "zhi", "dan",
                    "lu:", "you", "bo", "bao", "kuai", "tuo,duo", "yi", "qu",
                    "wen", "qu", "jiong", "bo", "zhao", "yuan", "peng", "zhou",
                    "ju", "zhu", "nu", "ju", "pi", "zang", "jia", "ling",
                    "zhen", "tai", "fu", "yang", "shi", "bi", "tuo", "tuo",
                    "si", "liu", "ma", "pian", "tao", "zhi", "rong", "teng",
                    "dong", "xun", "quan", "shen", "jiong", "er", "hai,xie",
                    "bo", "none", "yin", "luo", "none", "dan", "xie", "liu",
                    "ju", "song", "qin", "mang", "liang", "han", "tu", "xuan",
                    "tui", "jun", "e", "cheng", "xing", "ai", "lu", "zhui",
                    "zhou", "she", "pian", "kun", "tao", "lai", "zong", "ke",
                    "qi,ji", "qi", "yan", "fei", "sao", "yan", "jie,ge", "yao",
                    "wu", "pian", "cong", "pian", "qian", "fei", "huang",
                    "jian", "huo", "yu", "ti", "quan", "xia", "zong", "kui",
                    "rou", "si", "gua", "tuo,tan", "kui", "sou", "qian",
                    "cheng", "zhi", "liu", "pang", "teng", "xi", "cao", "du",
                    "yan", "yuan", "zou", "sao", "shan", "li", "zhi", "shuang",
                    "lu", "xi", "luo", "zhang", "mo", "ao", "can", "piao,biao",
                    "cong", "qu", "bi", "zhi", "yu", "xu", "hua", "bo", "su",
                    "xiao", "lin", "zhan", "dun", "liu", "tuo", "zeng", "tan",
                    "jiao", "tie", "yan", "luo", "zhan", "jing", "yi", "ye",
                    "tuo", "bin", "zou,zhou", "yan", "peng", "lu:", "teng",
                    "xiang", "ji", "shuang", "ju", "xi", "huan", "li", "biao",
                    "ma", "yu", "tuo,duo", "xun", "chi", "qu", "ri", "bo",
                    "lu:", "zang", "shi", "si", "fu", "ju", "zou", "zhu",
                    "tuo", "nu", "jia", "yi", "tai,dai", "xiao", "ma", "yin",
                    "jiao", "hua", "luo", "hai", "pian", "biao", "li", "cheng",
                    "yan", "xing", "qin", "jun", "qi", "qi", "ke", "zhui",
                    "zong", "su", "can", "pian", "zhi", "kui", "sao", "wu",
                    "ao", "liu", "qian", "shan", "piao,biao", "luo", "cong",
                    "zhan,chan", "zhou", "ji", "shuang", "xiang", "gu", "wei",
                    "wei", "wei", "yu", "gan", "yi", "ang", "tou,shai",
                    "jie,xie", "bo", "bi", "ci", "ti", "di", "ku", "hai",
                    "qiao", "hou", "kua", "ge", "tui", "geng", "pian", "bi",
                    "ke", "qia", "yu", "sui", "lou", "bo", "xiao", "bang",
                    "bo", "cuo", "kuan", "bin", "mo", "liao", "lou", "nao",
                    "du", "zang", "sui", "ti", "bin", "kuan", "lu", "gao",
                    "gao", "qiao", "kao", "qiao", "lao", "zao", "biao,shan",
                    "kun", "kun", "ti", "fang", "xiu", "ran", "mao", "dan",
                    "kun", "bin", "fa", "tiao", "pi", "zi", "fa", "ran", "ti",
                    "pao", "pi", "mao", "fu,fo", "er", "rong", "qu", "none",
                    "xiu", "gua", "ji", "peng", "zhua", "shao", "sha", "ti",
                    "li", "bin", "zong", "ti", "peng", "song", "zheng",
                    "quan,qian", "zong", "shun", "jian", "duo", "hu", "la",
                    "jiu", "qi", "lian", "zhen", "bin", "peng", "mo", "san",
                    "man", "man", "seng", "xu", "lie", "qian", "qian", "nong",
                    "huan", "kuai", "ning", "bin", "lie", "rang", "dou", "dou",
                    "nao", "hong", "xi", "dou", "kan", "dou", "dou", "jiu",
                    "chang", "yu", "yu", "li,ge", "juan", "fu", "qian", "gui",
                    "zong", "liu", "gui", "shang", "yu", "gui", "mei", "ji",
                    "qi", "jie", "kui", "hun", "ba", "po,tuo,bo", "mei", "xu",
                    "yan", "xiao", "liang", "yu", "tui", "qi", "wang", "liang",
                    "wei", "jian", "chi", "piao", "bi", "mo", "ji", "xu",
                    "chou", "yan", "zhan", "yu", "dao", "ren", "ji", "ba",
                    "hong", "tuo", "diao", "ji", "yu", "e", "que", "sha",
                    "hang", "tun", "mo", "gai", "shen", "fan", "yuan", "pi",
                    "lu", "wen", "hu", "lu", "za", "fang", "fen", "na", "you",
                    "none", "none", "he,ge", "xia", "qu", "han", "pi", "ling",
                    "tuo", "ba", "qiu", "ping", "fu", "bi", "ji", "wei", "ju",
                    "diao", "ba", "you", "gun", "pi", "nian", "xing", "tai",
                    "bao", "fu", "zha", "ju", "gu", "none", "none", "none",
                    "ta", "jie", "shua", "hou", "xiang", "er", "an", "wei",
                    "tiao", "zhu", "yin", "lie", "luo", "tong", "yi", "qi",
                    "bing", "wei", "jiao", "pu", "gui,xie", "xian", "ge",
                    "hui", "none", "none", "kao", "none", "duo", "jun", "ti",
                    "mian", "shao", "za", "suo", "qin", "yu", "nei", "zhe",
                    "gun", "geng", "none", "wu", "qiu", "ting", "fu", "huan",
                    "chou", "li", "sha", "sha", "gao", "meng", "none", "none",
                    "none", "none", "yong", "ni", "zi", "qi", "qing,zheng",
                    "xiang", "nei", "chun", "ji", "diao", "qie", "gu", "zhou",
                    "dong", "lai", "fei", "ni", "yi", "kun", "lu", "jiu",
                    "chang", "jing", "lun", "ling", "zou", "li", "meng",
                    "zong", "zhi", "nian", "none", "none", "none", "shi",
                    "sao", "hun", "ti", "hou", "xing", "ju", "la", "zong",
                    "ji", "bian", "bian", "huan", "quan", "ji", "wei", "wei",
                    "yu", "chun", "rou", "die", "huang", "lian", "yan", "qiu",
                    "qiu", "jian", "bi", "e", "yang", "fu", "sai,xi", "jian",
                    "ha,xia", "tuo", "hu", "none", "ruo", "none", "wen",
                    "jian", "hao", "wu", "pang", "sao", "liu", "ma", "shi",
                    "shi", "guan", "zi", "teng", "ta", "yao", "ge", "rong",
                    "qian", "qi", "wen", "ruo", "none", "lian", "ao", "le",
                    "hui", "min", "ji", "tiao", "qu", "jian", "sao", "man",
                    "xi", "qiu", "biao", "ji", "ji", "zhu", "jiang", "qiu",
                    "zhuan", "yong", "zhang", "kang", "xue", "bie", "jue",
                    "qu", "xiang", "bo", "jiao", "xun", "su", "huang", "zun",
                    "shan", "shan", "fan", "gui", "lin", "xun", "miao", "xi",
                    "none", "xiang", "fen", "guan", "hou", "kuai", "zei",
                    "sao", "zhan", "gan", "gui", "sheng", "li", "chang",
                    "none", "none", "ai", "ru", "ji", "xu", "huo", "none",
                    "li", "lie", "li", "mie", "zhen", "xiang", "e", "lu",
                    "guan", "li", "xian", "yu", "dao", "ji", "you", "tun",
                    "lu", "fang", "ba", "ke", "ba", "ping", "nian", "lu",
                    "you", "zha", "fu", "ba,bo", "bao", "hou", "pi", "tai",
                    "gui,xie", "jie", "kao", "wei", "er", "tong", "zei", "hou",
                    "kuai", "ji", "jiao", "xian", "zha", "xiang", "xun",
                    "geng", "li", "lian", "jian", "li", "shi", "tiao", "gun",
                    "sha", "huan", "jun", "ji", "yong", "qing,zheng", "ling",
                    "qi", "zou", "fei", "kun", "chang", "gu", "ni", "nian",
                    "diao", "jing", "shen", "shi", "zi", "fen", "die", "bi",
                    "chang", "ti", "wen", "wei", "sai", "e", "qiu", "fu",
                    "huang", "quan", "jiang", "bian", "sao", "ao", "qi", "ta",
                    "guan", "yao", "pang", "jian", "le", "biao", "xue", "bie",
                    "man", "min", "yong", "wei", "xi", "gui", "shan", "lin",
                    "zun", "hu", "gan", "li", "shan", "guan", "niao", "yi",
                    "fu", "li", "jiu", "bu", "yan", "fu", "diao", "ji", "feng",
                    "none", "gan", "shi", "feng", "ming", "bao", "yuan", "zhi",
                    "hu", "qian", "fu", "fen", "wen", "jian", "shi", "yu",
                    "fou", "yiao", "ju", "jue", "pi", "huan", "zhen", "bao",
                    "yan", "ya", "zheng", "fang", "feng", "wen", "ou", "te",
                    "jia", "nu", "ling", "mie", "fu", "tuo", "wen", "li",
                    "bian", "zhi", "ge", "yuan", "zi", "qu", "xiao", "chi,zhi",
                    "dan", "ju", "you", "gu", "zhong", "yu", "yang", "rong",
                    "ya", "zhi", "yu", "none", "ying", "zhui", "wu", "er",
                    "gua", "ai", "zhi", "yan", "heng", "jiao", "ji", "lie",
                    "zhu", "ren", "ti", "hong", "luo", "ru", "mou", "ge",
                    "ren", "jiao", "xiu", "zhou", "chi", "luo", "none", "none",
                    "none", "luan", "jia", "ji", "yu", "huan", "tuo", "bu",
                    "wu", "juan", "yu", "bo", "xun", "xun", "bi", "xi", "jun",
                    "ju", "tu", "jing", "ti", "e", "e", "kuang", "hu,gu", "wu",
                    "shen", "la", "none", "none", "lu", "bing", "shu", "fu",
                    "an", "zhao", "peng", "qin", "qian", "bei", "diao", "lu",
                    "que,qiao", "jian", "ju", "tu", "ya", "yuan", "qi", "li",
                    "ye", "zhui", "kong", "duo", "kun", "sheng", "qi", "jing",
                    "ni", "e", "jing", "zi", "lai", "dong", "qi", "chun",
                    "geng", "ju", "qu", "none", "none", "ji", "shu", "none",
                    "chi", "miao", "rou", "fu", "qiu", "ti", "hu", "ti", "e",
                    "jie", "mao", "fu", "chun", "tu", "yan", "he", "yuan",
                    "pian,bin", "yun", "mei", "hu", "ying", "dun", "mu,wu",
                    "ju", "none", "cang", "fang", "ge", "ying", "yuan", "xuan",
                    "weng", "shi", "he,hao", "chu", "tang", "xia", "ruo",
                    "liu", "ji", "gu,hu", "jian", "zhun", "han", "zi", "ci",
                    "yi,ni", "yao", "yan", "ji", "li,piao", "tian", "kou",
                    "ti", "ti", "ni", "tu", "ma", "jiao", "liu", "zhen",
                    "chen", "li", "zhuan", "zhe", "ao", "yao", "yi", "ou",
                    "chi", "zhi", "liao,liu", "rong", "lou", "bi", "shuang",
                    "zhuo", "yu", "wu", "jue", "yin", "tan", "si", "jiao",
                    "yi", "hua", "bi", "ying", "su", "huang", "fan", "jiao",
                    "liao", "yan", "kao", "jiu", "xian", "xian", "tu", "mai",
                    "zun", "yu", "ying", "lu", "tuan", "xian", "xue", "yi",
                    "pi", "shu", "luo", "qi", "yi", "ji", "zhe", "yu", "zhan",
                    "ye", "yang", "pi", "ning", "hu", "mi", "ying", "meng",
                    "di", "yue", "yu", "lei", "bo", "lu", "he", "long",
                    "shuang", "yue", "ying", "guan", "qu", "li", "luan",
                    "niao,diao", "jiu", "ji", "yuan", "ming", "shi", "ou",
                    "ya", "cang", "bao", "zhen", "gu", "dong", "lu", "ya",
                    "xiao", "yang", "ling", "chi", "qu", "yuan", "xue", "tuo",
                    "si", "zhi", "er", "gua", "xiu", "heng", "zhou", "ge",
                    "luan", "hong", "wu", "bo", "li", "juan", "hu,gu", "e",
                    "yu", "xian", "ti", "wu", "que", "miao", "an", "kun",
                    "bei", "peng", "qian", "chun", "geng", "yuan", "su", "hu",
                    "he", "e", "gu,hu", "qiu", "ci", "mei", "wu", "yi", "yao",
                    "weng", "liu", "ji", "yi", "jian", "he", "yi", "ying",
                    "zhe", "liu", "liao", "jiao", "jiu", "yu", "lu", "huan",
                    "zhan", "ying", "hu", "meng", "guan", "shuang", "lu",
                    "jin", "ling", "jian", "xian", "cuo", "jian", "jian",
                    "yan", "cuo", "lu", "you", "cu", "ji", "biao", "cu", "pao",
                    "zhu", "jun,qun", "zhu", "jian,qian", "mi", "mi", "wu",
                    "liu", "chen", "jun,qun", "lin", "ni", "qi", "lu", "jiu",
                    "jun,qun", "jing", "li", "xiang", "yan", "jia", "mi", "li",
                    "she", "zhang", "lin", "jing", "qi", "ling", "yan", "cu",
                    "mai", "mai", "ge", "chao", "fu", "mian", "mian", "fu",
                    "pao", "qu", "qu", "mou", "fu", "xian", "lai", "qu",
                    "mian", "chi,li", "feng", "fu", "qu", "mian", "ma",
                    "ma,me,mo", "mo,me", "hui", "none", "zou", "nen", "fen",
                    "huang", "huang", "jin", "guang", "tian", "tou", "hong",
                    "xi", "kuang", "hong", "shu", "li", "nian", "chi,li",
                    "hei", "hei", "yi", "qian", "zhen", "xi", "tuan", "mo",
                    "mo", "qian", "dai", "chu", "you", "dian", "yi", "xia",
                    "yan", "qu", "mei", "yan", "qing,jing", "yu", "li", "dang",
                    "du", "can", "yin", "an", "yan", "tan", "an", "zhen",
                    "dai", "can", "yi", "mei", "dan", "yan", "du", "lu", "zhi",
                    "fen", "fu", "fu", "min,mian", "min,mian", "yuan", "cu",
                    "qu", "chao", "wa", "zhu", "zhi", "mang", "ao", "bie",
                    "tuo", "bi", "yuan", "chao", "tuo", "ding", "mi", "nai",
                    "ding", "zi", "gu,hu", "gu", "dong", "fen", "tao", "yuan",
                    "pi", "chang", "gao", "qi", "yuan", "tang", "teng", "shu",
                    "shu", "fen", "fei", "wen", "ba", "diao", "tuo", "tong",
                    "qu", "sheng", "shi", "you", "shi", "ting", "wu", "nian",
                    "jing", "hun", "ju", "yan", "tu", "si", "xi", "xian",
                    "yan", "lei", "bi", "yao", "yan,qui", "han", "hui", "wu",
                    "hou", "xi", "ge", "zha", "xiu", "weng", "zha", "nong",
                    "nang", "qi,zhai", "zhai", "ji", "zi,ji", "ji", "ji",
                    "qi,ji", "ji", "chi", "chen", "chen", "he", "ya", "ken",
                    "xie", "bao", "ze", "shi", "zi", "chi", "nian", "ju",
                    "tiao", "ling", "ling", "chu", "quan", "xie", "yin,ken",
                    "nie", "jiu", "nie", "chuo", "kun", "yu", "chu", "yi",
                    "ni", "cuo", "chuo", "qu", "nian", "xian", "yu", "e", "wo",
                    "yi", "chi", "zou", "dian", "chu", "jin", "ya", "chi",
                    "chen", "he", "yin", "ju", "ling", "bao", "tiao", "zi",
                    "yin,ken", "yu", "chuo", "qu", "wo", "long", "pang",
                    "gong", "pang", "yan", "long", "long", "gong", "kan", "ta",
                    "ling", "ta", "long", "gong", "kan", "gui,jun,qiu", "qiu",
                    "bie", "gui,jun,qiu", "yue", "chui", "he", "jue", "xie",
                    "yue"
            };
        }
    }
}
