
package cn.com.nd.momo.api.util;

/**
 * 多音节，从0x6ECF到0x7F36
 * 
 * @author chenjp
 */
public class MultiPinYin3 {
    public static String[] pinyinArray = null;

    private MultiPinYin3() {
    };

    static {
        if (null == pinyinArray) {
            pinyinArray = new String[] {
                    "fu", "jie", "hua,gu", "ge", "zi", "tao",
                    "teng", "sui", "bi", "jiao", "hui", "gun", "yin", "gao",
                    "long,shuang", "zhi", "yan", "she", "man", "ying", "chun",
                    "lu:", "lan", "luan", "xiao", "bin", "tan", "yu", "xiu",
                    "hu", "bi", "biao", "zhi", "jiang", "kou", "shen", "shang",
                    "di", "mi", "ao", "lu", "hu,xu", "hu", "you", "chan",
                    "fan", "yong", "gun", "man", "qing", "yu", "piao", "ji",
                    "ya", "jiao", "qi,qu,xi", "xi", "ji", "lu", "lu:,lou",
                    "long", "jin", "guo", "cong", "lou", "zhi", "gai", "qiang",
                    "li", "yan", "cao", "jiao", "cong", "chun", "tuan", "ou",
                    "teng", "ye", "xi", "mi", "tang", "mo", "shang", "han",
                    "lian", "lan", "wa", "li", "qian", "feng", "xuan", "yi",
                    "man", "zi", "mang", "kang", "luo,ta", "peng", "shu",
                    "zhang", "zhang", "chong", "xu", "huan", "kuo,huo", "jian",
                    "yan", "chuang,shuang", "liao", "cui", "ti", "yang",
                    "jiang", "cong", "ying", "hong", "xiu", "shu", "guan",
                    "ying", "xiao", "none", "none", "xu", "lian", "zhi", "wei",
                    "pi", "yu", "jiao", "po", "xiang", "hui", "jie", "wu",
                    "pa", "ji", "pan", "wei", "xiao,su", "qian", "qian", "xi",
                    "lu", "xi", "sun", "dun", "huang", "min", "run", "su",
                    "liao,lao", "zhen", "zhong", "yi", "di", "wan", "dan",
                    "tan", "chao", "xun", "kui,hui", "none", "shao", "tu",
                    "zhu", "sa", "hei", "bi", "shan", "chan", "chan", "shu",
                    "tong", "pu", "lin", "wei", "se", "se", "cheng,deng",
                    "jiong", "cheng,deng", "hua", "jiao", "lao", "che", "gan",
                    "cun", "heng", "si", "shu", "peng", "han", "yun", "liu",
                    "hong", "fu", "hao", "he", "xian", "jian", "shan", "xi",
                    "ao", "lu", "lan", "none", "yu", "lin", "min,mian,sheng",
                    "zao", "dang", "huan", "ze", "xie", "yu", "li", "shi",
                    "xue", "ling", "man", "zi", "yong", "kuai,hui", "can",
                    "lian", "dian", "ye", "ao", "huan", "lian", "chan", "man",
                    "dan", "dan,tan", "yi", "sui", "pi", "ju", "ta", "qin",
                    "ji", "zhuo", "lian", "nong", "guo", "jin", "fen", "se",
                    "ji", "sui", "hui", "chu", "ta", "song", "ding", "se",
                    "zhu", "lai", "bin", "lian", "mi", "shi", "shu", "mi",
                    "ning,neng", "ying", "ying,xing", "meng", "jin", "qi",
                    "bi", "ji", "hao", "ru", "zui,cui", "wo", "tao", "yin",
                    "yin", "dui", "ci", "huo", "jing", "lan", "jun", "ai",
                    "pu", "zhuo", "wei", "bin", "gu", "qian", "xing", "bin",
                    "kuo", "fei", "none", "bin", "jian", "dui,wei", "luo",
                    "luo", "lu:", "li", "you", "yang", "lu", "si", "jie",
                    "ying", "du", "wang", "hui", "xie", "pan", "shen", "biao",
                    "chan", "mie", "liu", "jian", "pu,bao", "se", "cheng",
                    "gu", "bin,pin", "huo", "xian", "lu", "qin", "han", "ying",
                    "rong", "li", "jing", "xiao", "ying", "sui", "wei", "xie",
                    "huai", "hao", "zhu", "long,shuang", "lai", "dui", "fan",
                    "hu", "lai", "none", "none", "ying", "mi", "ji", "lian",
                    "jian", "ying", "fen", "lin", "yi", "jian", "yue", "chan",
                    "dai", "rang", "jian", "lan", "fan", "shuang", "yuan",
                    "zhuo", "feng", "she", "lei", "lan", "cong", "qu", "yong",
                    "qian", "fa", "guan", "que", "yan", "hao", "none", "sa",
                    "zan", "luan", "yan", "li", "mi", "dan", "tan", "dang",
                    "jiao", "chan", "none", "hao", "ba", "zhu", "lan", "lan",
                    "nang", "wan", "luan", "quan", "xian", "yan", "gan", "yan",
                    "yu", "huo", "biao", "mie", "guang", "deng", "hui", "xiao",
                    "xiao", "none", "hong", "ling", "zao", "zhuan", "jiu",
                    "zha", "xie", "chi", "zhuo", "zai", "zai", "can", "yang",
                    "qi", "zhong", "fen", "niu", "gui,jiong", "wen", "po",
                    "yi", "lu", "chui", "pi", "kai", "pan", "yan", "kai",
                    "pang", "mu", "chao", "liao", "gui,que", "kang", "dun",
                    "guang", "xin", "zhi", "guang", "xin", "wei", "qiang",
                    "bian", "da", "xia", "zheng", "zhu", "ke", "zhao", "fu",
                    "ba", "duo", "duo", "ling", "zhuo", "xuan", "ju", "tan",
                    "pao,bao", "jiong", "pao", "tai", "tai", "bing", "yang",
                    "tong,dong", "han", "zhu", "zha", "dian", "wei", "shi",
                    "lian", "chi", "ping", "none", "hu", "shuo", "lan", "ting",
                    "jiao", "xu", "xing", "quan", "lie", "huan", "yang",
                    "xiao", "xiu", "xian", "yin", "wu", "zhou", "yao", "shi",
                    "wei", "tong", "tong", "zai", "kai", "hong", "luo,lao",
                    "xia", "zhu", "xuan", "zheng", "po", "yan,yin", "hui",
                    "guang", "zhe", "hui", "kao", "none", "fan", "shao", "ye",
                    "hui", "none", "tang", "jin", "re", "none", "xi", "fu",
                    "jiong", "che", "pu", "jing,ting", "zhuo", "ting", "wan",
                    "hai", "peng", "lang", "shan", "hu", "feng", "chi", "rong",
                    "hu", "none", "shu", "lang", "xun", "xun", "jue", "xiao",
                    "xi", "yan", "han", "zhuang", "qu,jun", "di,ti", "xie",
                    "qi", "wu", "none", "none", "han", "yan", "huan", "men",
                    "ju", "dao,tao", "bei", "fen", "lin", "kun", "hun", "chun",
                    "xi", "cui", "wu,mo", "hong", "ju", "fu", "yue", "jiao",
                    "cong", "feng", "ping", "qiong", "cui", "xi", "qiong",
                    "xin", "zhuo,chao", "yan", "yan", "yi", "jue", "yu",
                    "gang", "ran", "pi", "yan", "none", "sheng", "chang",
                    "shao", "none", "none", "none", "none", "chen", "he",
                    "kui", "zhong", "duan", "ya", "hui", "feng", "lian",
                    "xuan", "xing", "huang", "jiao", "jian", "bi", "ying",
                    "zhu", "wei", "tuan", "tian", "xi", "nuan,xuan", "nuan",
                    "chan", "yan", "jiong", "jiong", "yu", "mei", "sha", "wu",
                    "ye", "xin", "qiong", "rou", "mei", "huan", "xu", "zhao",
                    "wei", "fan", "qiu", "sui", "yang", "lie", "zhu", "none",
                    "gao", "gua", "bao", "hu", "yun", "xia", "none", "none",
                    "bian", "wei", "tui", "tang", "chao", "shan", "yun", "bo",
                    "huang", "xie", "xi", "wu", "xi", "yun", "he", "he", "xi",
                    "yun", "xiong", "nai", "kao", "none", "yao", "xun", "ming",
                    "lian", "ying", "wen", "rong", "none", "none", "qiang",
                    "liu", "xi", "bi", "biao", "cong", "lu", "jian",
                    "shu,shou", "yi", "lou", "feng", "sui", "yi", "teng",
                    "jue", "zong", "yun", "hu", "yi", "zhi", "ao", "wei",
                    "liao", "han", "ou", "re", "jiong", "man", "none", "shang",
                    "cuan", "zeng", "jian", "xi", "xi", "xi", "yi", "xiao",
                    "chi", "huang", "chan", "ye", "qian", "ran", "yan", "xian",
                    "qiao", "zun", "deng", "dun", "shen", "jiao", "fen", "si",
                    "liao", "yu", "lin", "tong", "shao", "fen", "fan", "yan",
                    "xun", "lan", "mei", "tang", "yi", "jing", "men", "none",
                    "none", "ying", "yu", "yi", "xue", "lan", "tai", "zao",
                    "can", "sui", "xi", "que", "cong", "lian", "hui", "zhu",
                    "xie", "ling", "wei", "yi", "xie", "zhao", "hui", "none",
                    "none", "lan", "ru", "xian", "kao", "xun", "jin", "chou",
                    "dao,tao", "yao", "he", "lan", "biao", "rong", "li", "mo",
                    "bao", "ruo", "di", "lu:", "ao", "xun", "kuang", "shuo",
                    "none", "li", "lu", "jue", "liao", "yan", "xi", "xie",
                    "long", "yan", "none", "rang,shang", "yue", "lan", "cong",
                    "jue,jiao", "tong", "guan", "none", "che", "mi", "tang",
                    "lan", "zhu", "lan", "ling", "cuan", "yu", "zhua,zhao",
                    "lan", "pa", "zheng", "pao", "zhao", "yuan", "ai", "wei",
                    "none", "jue", "jue", "fu", "ye", "ba", "die", "ye", "yao",
                    "zu", "shuang", "er", "pan,qiang,ban", "chuan", "ke",
                    "zang", "zang", "qiang", "die", "qiang", "pian", "ban",
                    "pan", "shao", "jian", "pai", "du", "yong", "tou", "tou",
                    "bian", "die", "bang", "bo", "bang", "you", "none", "du",
                    "ya", "cheng", "niu", "cheng", "pin", "jiu", "mou,mu",
                    "ta", "mu", "lao", "ren", "mang", "fang", "mao", "mu",
                    "ren", "wu", "yan", "fa", "bei", "si", "jian", "gu", "you",
                    "gu", "sheng", "mu", "di", "qian", "quan", "quan", "zi",
                    "te", "xi", "mang", "keng", "qian", "wu", "gu", "xi", "li",
                    "li", "pou", "ji", "gang", "zhi", "ben", "quan", "run",
                    "du", "ju", "jia", "jian,qian", "feng", "pian", "ke", "ju",
                    "kao,di", "chu", "xi", "bei", "luo", "jie", "ma", "san",
                    "wei", "li", "dun", "tong", "se", "jiang", "xi", "li",
                    "du", "lie", "pi", "piao", "bao", "xi", "chou", "wei",
                    "kui", "chou", "quan", "quan", "ba", "fan", "qiu", "bo",
                    "chai", "chuo", "an,han", "jie", "zhuang", "guang", "ma",
                    "you", "kang", "bo", "hou", "ya", "han", "huan", "zhuang",
                    "yun", "kuang", "niu", "di", "qing", "zhong", "yun", "bei",
                    "pi", "ju", "ni", "sheng", "pao", "xia", "tuo", "hu",
                    "ling", "fei", "pi", "ni", "sheng", "you", "gou", "yue",
                    "ju", "dan", "bo", "gu", "xian", "ning", "huan", "hen",
                    "jiao", "he,hao,mo", "zhao", "ji", "huan", "shan", "ta",
                    "rong", "shou", "tong", "lao", "du", "xia", "shi", "kuai",
                    "zheng", "yu", "sun", "yu", "bi", "mang", "xi", "juan",
                    "li", "xia", "yin", "suan", "lang", "bei", "zhi", "yan",
                    "sha", "li", "zhi", "xian", "jing", "han", "fei", "yao",
                    "ba,pi", "qi", "ni", "biao", "yin", "li", "lie", "jian",
                    "qiang", "kun", "yan", "guo", "zong", "mi", "chang", "yi",
                    "zhi", "zheng", "ya", "meng", "cai", "cu", "she", "lie",
                    "none", "luo", "hu", "zong", "hu", "wei", "feng", "wo",
                    "yuan", "xing", "zhu", "mao", "wei", "yuan", "xian",
                    "tuan", "ya", "nao", "xie,he", "jia", "hou", "bian", "you",
                    "you", "mei", "cha", "yao", "sun", "bo", "ming", "hua",
                    "yuan", "sou", "ma", "yuan", "dai", "yu", "shi", "hao",
                    "none", "yi", "zhen", "chuang", "hao", "man", "jing",
                    "jiang", "mo", "zhang", "chan", "ao", "ao", "hao", "cui",
                    "ben", "jue", "bi", "bi", "huang", "bu", "lin", "yu",
                    "tong", "yao", "liao", "shuo", "xiao", "shou", "none",
                    "xi", "ge", "juan", "du", "hui", "kuai", "xian", "xie",
                    "ta", "xian", "xun", "ning", "bian", "huo", "nou", "meng",
                    "lie", "nao", "guang", "shou", "lu", "ta", "xian", "mi",
                    "rang", "huan", "nao", "luo", "xian", "qi", "qu", "xuan",
                    "miao", "zi", "lu:,shuai,shuo", "lu", "yu", "su", "wang",
                    "qiu", "ga", "ding", "le", "ba", "ji", "hong", "di",
                    "chuan", "gan", "jiu", "yu", "qi", "yu", "yang,chang",
                    "ma", "hong", "wu", "fu", "min,wen", "jie", "ya",
                    "bin,fen", "bian", "beng", "yue", "jue", "yun", "jue",
                    "wan", "jian", "mei", "dan", "pi", "wei", "huan", "xian",
                    "qiang", "ling", "dai", "yi", "an", "ping", "dian", "fu",
                    "xuan", "xi", "bo", "ci", "gou", "jia", "shao", "po", "ci",
                    "ke", "ran", "sheng", "shen", "yi", "zu", "jia", "min",
                    "shan", "liu", "bi", "zhen", "zhen", "jue", "fa", "long",
                    "jin", "jiao", "jian", "li", "guang", "xian", "zhou",
                    "gong", "yan", "xiu", "yang", "xu", "luo", "su", "zhu",
                    "qin", "ken", "xun", "bao", "er", "xiang", "yao", "xia",
                    "heng,hang", "gui", "chong", "xu", "ban", "pei", "none",
                    "dang", "ying", "hun,hui", "wen", "e", "cheng", "ti,di",
                    "wu", "wu", "cheng", "jun", "mei", "bei", "ting", "xian",
                    "chuo", "han", "xuan", "yan", "qiu", "quan", "lang", "li",
                    "xiu", "fu", "liu", "ya,ye", "xi", "ling", "li", "jin",
                    "lian", "suo", "suo", "none", "wan", "dian", "bing",
                    "zhan", "cui", "min", "yu", "ju", "chen", "lai", "wen",
                    "sheng", "wei", "dian", "chu", "zhuo,zuo", "pei", "cheng",
                    "hu", "qi", "e", "kun", "chang", "qi", "beng", "wan", "lu",
                    "cong", "guan", "yan", "diao", "bei", "lin", "qin", "pi",
                    "pa,ba", "qiang", "zhuo", "qin", "fa", "none", "qiong",
                    "du", "jie", "hun,hui", "yu", "mao,mei", "mei", "chun",
                    "xuan", "ti", "xing", "dai", "rou", "min", "zhen", "wei",
                    "ruan", "huan", "xie", "chuan", "jian", "zhuan", "yang",
                    "lian", "quan", "xia", "duan", "yuan", "ye", "nao", "hu",
                    "ying", "yu", "huang", "rui", "se", "liu", "none", "rong",
                    "suo", "yao", "wen", "wu", "jin", "jin", "ying", "ma",
                    "tao", "liu", "tang", "li", "lang", "gui", "tian", "qiang",
                    "cuo", "jue", "zhao", "yao", "ai", "bin", "tu", "chang",
                    "kun", "zhuan", "cong", "jin", "yi", "cui", "cong", "qi",
                    "li", "ying", "suo", "qiu", "xuan", "ao", "lian", "man",
                    "zhang", "yin", "none", "ying", "wei", "lu", "wu", "deng",
                    "none", "zeng", "xun", "qu", "dang", "lin", "liao",
                    "qiong", "su", "huang", "gui", "pu", "jing", "fan", "jin",
                    "liu", "ji", "none", "jing", "ai", "bi", "can", "qu",
                    "zao", "dang", "jiao", "gun", "tan", "hui", "huan", "se",
                    "sui", "tian", "none", "yu", "jin", "fu", "bin", "shu",
                    "wen", "zui", "lan", "xi", "ji", "xuan", "ruan", "huo",
                    "gai", "lei", "du", "li", "zhi", "rou", "li", "zan",
                    "qiong", "zhe", "gui", "sui", "la", "long", "lu", "li",
                    "zan", "lan", "ying", "mi", "xiang", "xi", "guan", "dao",
                    "zan", "huan", "gua", "bao", "die", "pao", "hu", "zhi",
                    "piao", "ban", "rang", "li", "wa", "none", "jiang,hong",
                    "qian,wa", "ban", "pen", "fang", "dan", "weng", "ou",
                    "none", "none", "none", "hu", "ling", "yi", "ping", "ci",
                    "none", "juan", "chang", "chi", "none", "dang", "meng",
                    "bu", "chui", "ping", "bian", "zhou", "zhen", "none", "ci",
                    "ying", "qi", "xian", "lou", "di", "ou", "meng", "zhuan",
                    "beng", "lin", "zeng", "wu", "pi", "dan", "weng", "ying",
                    "yan", "gan", "dai", "shen", "tian", "tian", "han",
                    "chang", "sheng", "qing", "shen", "chan", "chan", "rui",
                    "sheng", "su", "shen", "yong", "shuai", "lu", "fu", "yong",
                    "beng", "none", "ning", "tian", "you", "jia", "shen",
                    "zha", "dian", "fu", "nan", "dian", "ping", "ding,ting",
                    "hua", "ting,ding", "quan", "zai", "meng", "bi", "qi",
                    "liu", "xun", "liu", "chang", "mu", "yun", "fan", "fu",
                    "geng", "tian", "jie", "jie", "quan", "wei", "fu", "tian",
                    "mu", "none", "pan", "jiang", "wa", "da", "nan", "liu",
                    "ben", "zhen", "chu,xu", "mu", "mu", "ce", "none", "gai",
                    "bi", "da", "zhi", "lu:e", "qi,xi", "lu:e", "pan", "none",
                    "fan,pan", "hua", "yu", "yu", "mu", "jun", "yi", "liu",
                    "she", "die", "chou", "hua", "dang", "chuo", "ji", "wan",
                    "jiang", "cheng", "chang", "tun", "lei", "ji", "cha",
                    "liu", "die", "tuan", "lin", "jiang", "jiang", "chou",
                    "bo", "die", "die", "pi,shu,ya", "nie", "dan", "shu",
                    "shu", "zhi", "yi", "chuang", "nai", "ding", "bi", "jie",
                    "liao", "gong,gang", "ge", "jiu", "zhou", "xia", "shan",
                    "xu", "nu:e,yao", "li", "yang", "chen", "you", "ba", "jie",
                    "jue", "xi", "xia", "cui", "bi", "yi", "li", "zong",
                    "chuang", "feng", "zhu", "pao", "pi", "gan", "ke", "ci",
                    "xie", "qi", "dan", "zhen", "fa", "zhi", "teng", "ju",
                    "ji", "fei", "ju", "dian", "jia", "xuan,xian", "zha",
                    "bing", "nie", "zheng", "yong", "jing", "quan", "chong",
                    "tong", "yi", "jie", "wei", "hui", "duo", "yang", "chi",
                    "zhi", "hen", "ya", "mei", "dou", "jing", "xiao", "tong",
                    "tu", "mang", "pi", "xiao", "suan", "pu", "li", "zhi",
                    "cuo", "duo", "wu", "sha", "lao", "shou", "huan", "xian",
                    "yi", "peng", "zhang", "guan", "tan", "fei", "ma", "lin",
                    "chi", "ji", "tian", "an", "chi", "bi", "bi", "min", "gu",
                    "dui", "e", "wei", "yu", "cui", "ya", "zhu", "xi", "dan",
                    "shen", "zhong", "ji,zhi", "yu", "hou", "feng", "la",
                    "yang", "shen", "tu", "yu", "gua", "wen", "huan", "ku",
                    "jia,xia", "yin", "yi", "lou", "sao", "jue", "chi", "xi",
                    "guan", "yi", "wen", "ji", "chuang", "ban", "lei", "liu",
                    "chai,cuo", "shou", "nu:e,yao", "dian", "da", "bie", "tan",
                    "zhang", "biao", "shen", "cu", "luo", "yi", "zong", "chou",
                    "zhang", "zhai", "sou", "suo", "que", "diao", "lou", "lou",
                    "mo", "jin", "yin", "ying", "huang", "fu", "liao", "long",
                    "qiao", "liu", "lao", "xian", "fei", "dan", "yin", "he",
                    "ai,yan", "ban", "xian", "guan", "guai", "nong", "yu",
                    "wei", "yi", "yong", "pi", "lei", "li,ji", "shu", "dan",
                    "lin", "dian", "lin", "lai", "bie", "ji", "chi", "yang",
                    "xuan", "jie", "zheng", "none", "li", "huo", "lai", "ji",
                    "dian", "xian,xuan", "ying", "yin", "qu", "yong", "tan",
                    "dian", "luo", "luan", "luan", "bo", "none", "gui", "po",
                    "fa", "deng", "fa", "bai", "bai,bo", "qie", "bi", "zao",
                    "zao", "mao", "de,di", "pa", "jie", "huang", "gui", "ci",
                    "ling", "gao", "mo", "ji", "jiao", "peng", "gao", "ai",
                    "e", "hao", "han", "bi", "wan,huan", "chou", "qian", "xi",
                    "ai", "jiong", "hao", "huang", "hao", "ze", "cui", "hao",
                    "xiao", "ye", "po", "hao", "jiao", "ai", "xing", "huang",
                    "li", "piao", "he", "jiao", "pi", "gan", "pao", "zhou",
                    "jun", "qiu", "cun", "que", "zha", "gu", "jun", "jun",
                    "zhou", "zha", "gu", "zhan", "du", "min", "qi", "ying",
                    "yu", "bei", "zhao", "zhong", "pen", "he", "ying", "he",
                    "yi", "bo", "wan", "he", "ang", "zhan", "yan", "jian",
                    "he", "yu", "kui", "fan", "gai,ge", "dao", "pan", "fu",
                    "qiu", "sheng,cheng", "dao", "lu", "zhan", "meng,ming",
                    "lu", "jin", "xu", "jian", "pan", "guan", "an", "lu", "xu",
                    "zhou", "dang", "an", "gu", "li", "mu", "ding", "gan",
                    "xu", "mang", "mang", "zhi", "qi", "wan", "tian", "xiang",
                    "dun", "xin", "xi", "pan", "feng", "dun,shun", "min",
                    "ming", "sheng,xing", "shi", "yun", "mian", "pan", "fang",
                    "miao", "dan", "mei", "mao", "kan", "xian", "kou", "shi",
                    "yang", "zheng", "yao", "shen", "huo", "da", "zhen",
                    "kuang", "ju", "shen", "yi", "sheng", "mei", "mo", "zhu",
                    "zhen", "zhen", "mian", "di", "yuan", "die", "yi", "zi",
                    "zi", "chao", "zha", "xuan", "bing", "mi", "long", "sui",
                    "tong", "mi", "die", "yi", "er", "ming", "xuan", "chi",
                    "kuang", "juan", "mou", "zhen", "tiao", "yang", "yan",
                    "mo", "zhong", "mai", "zhe,zhuo,zhao", "zheng", "mei",
                    "suo", "shao", "han", "huan", "di", "cheng", "cuo", "juan",
                    "e", "wan", "xian", "xi", "kun", "lai", "jian", "shan",
                    "tian", "hun", "wan", "ling", "shi", "qiong", "lie",
                    "ya,ai", "jing", "zheng", "li", "lai", "sui", "juan",
                    "shui", "sui", "du", "pi", "pi,bi", "mu", "hun", "ni",
                    "lu", "gao", "jie", "cai", "zhou", "yu", "hun", "ma",
                    "xia", "xing", "hui", "gun", "none", "chun", "jian", "mei",
                    "du", "hou", "xuan", "ti", "kui", "gao", "rui", "mao",
                    "xu", "fa", "wen", "miao", "chou", "kui", "mi", "weng",
                    "kou", "dang", "chen", "ke", "sou", "xia", "qiong", "mao",
                    "ming", "man", "shui", "ze", "zhang", "yi", "diao", "kou",
                    "mo", "shun", "cong", "lou", "chi", "man", "piao", "cheng",
                    "ji", "meng", "huan", "run", "pie", "xi", "qiao,ya", "pu",
                    "zhu", "deng", "shen", "shun", "liao", "che", "xian",
                    "kan", "ye", "xu", "tong", "wu", "lin", "kui", "jian",
                    "ye", "ai", "hui", "zhan", "jian", "gu", "zhao", "ju,qu",
                    "wei", "chou", "ji", "ning", "xun", "yao", "huo", "meng",
                    "mian", "bin,pin", "mian", "li", "guang", "jue", "xuan",
                    "mian", "huo", "lu", "meng", "long", "guan", "man", "xi",
                    "chu", "tang", "kan", "zhu", "mao", "jin,qin,guan", "lin",
                    "yu", "shuo", "ce", "jue", "shi", "yi", "shen", "zhi",
                    "hou", "shen", "ying", "ju", "zhou", "jiao", "cuo", "duan",
                    "ai", "jiao", "zeng", "huo", "bai,pai", "shi,dan", "ding",
                    "qi", "ji", "zi", "gan", "wu", "tuo", "ku", "qiang", "xi",
                    "fan", "kuang", "dang", "ma", "sha", "dan", "jue", "li",
                    "fu", "min", "nuo", "hua,xu", "kang", "zhi", "qi,qie",
                    "kan", "jie", "fen", "e", "ya", "pi", "zhe", "yan", "sui",
                    "zhuan", "che", "dun", "pan", "yan", "none", "feng", "fa",
                    "mo", "zha,zuo", "qu", "yu", "ke", "tuo", "tuo", "di",
                    "zhai", "zhen", "e", "fu,fei", "mu", "zhu", "la,li",
                    "bian", "nu", "ping", "peng", "ling", "pao", "le", "po",
                    "bo", "po", "shen", "za", "ai", "li", "long", "tong",
                    "none", "li", "kuang", "chu", "keng", "quan", "zhu",
                    "kuang", "gui,huo", "e", "nao", "jia", "lu", "wei,kui",
                    "ai", "luo,ge", "ken", "xing", "yan", "dong", "peng", "xi",
                    "none", "hong", "shuo", "xia", "qiao", "none", "wei",
                    "qiao", "none", "keng", "xiao", "que", "chan", "lang",
                    "hong", "yu", "xiao", "xia", "mang", "long", "none", "che",
                    "che", "wo", "liu", "ying", "mang", "que", "yan", "cuo",
                    "kun", "yu", "none", "none", "lu", "chen", "jian", "none",
                    "song", "zhuo", "keng", "peng", "yan", "zhui", "kong",
                    "ceng", "qi", "zong", "qing", "lin", "jun", "bo", "ding",
                    "min", "diao", "jian", "he", "liu,lu", "ai", "sui", "que",
                    "ling", "bei", "yin", "dui", "wu", "qi", "lun", "wan",
                    "dian", "gang", "bei", "qi", "chen", "ruan", "yan", "die",
                    "ding", "zhou", "tuo", "jie", "ying", "bian", "ke", "bi",
                    "wei", "shuo,shi", "zhen", "duan", "xia", "dang", "ti",
                    "nao", "peng", "jian", "di", "tan", "cha", "none", "qi",
                    "none", "feng", "xuan", "que", "que", "ma", "gong", "nian",
                    "su", "e", "ci", "liu", "si", "tang", "bang,pang", "hua",
                    "pi", "wei", "sang", "lei", "cuo", "tian", "xia", "xi",
                    "lian", "pan", "wei", "yun", "dui", "zhe", "ke", "la",
                    "none", "qing", "gun", "zhuan", "chan", "qi", "ao", "peng",
                    "lu", "lu", "kan", "qiang", "chen", "yin", "lei", "biao",
                    "qi", "mo", "qi", "cui", "zong", "qing", "chuo", "none",
                    "ji", "shan", "lao", "qu", "zeng", "deng", "jian", "xi",
                    "lin", "ding", "dian", "huang", "pan", "za", "qiao", "di",
                    "li", "jian", "jiao", "xi", "zhang", "qiao", "dun", "jian",
                    "yu", "zhui", "he", "huo", "zhai", "lei", "ke", "chu",
                    "ji", "que", "dang", "wo,yi", "jiang", "pi", "pi", "yu",
                    "pin", "qi", "ai", "ke", "jian", "yu", "ruan", "meng",
                    "pao", "zi", "bo", "none", "mie", "ca", "xian",
                    "kuang,gong", "lei", "lei", "zhi", "li", "li", "fan",
                    "que", "pao", "ying", "li", "long", "long", "mo", "bo",
                    "shuang", "guan", "lan", "zan", "yan", "shi", "shi", "li",
                    "reng", "she", "yue", "si", "qi", "ta", "ma", "xie", "yao",
                    "xian", "zhi,qi", "qi", "zhi", "beng", "shu", "chong",
                    "none", "yi", "shi", "you", "zhi", "tiao", "fu", "fu",
                    "mi", "zu", "zhi", "suan", "mei", "zuo", "qu", "hu", "zhu",
                    "shen", "sui", "ci", "chai", "mi,ni", "lu:", "yu", "xiang",
                    "wu", "tiao", "piao", "zhu", "gui", "xia", "zhi",
                    "ji,zhai", "gao", "zhen", "gao", "shui", "jin", "zhen",
                    "gai,jie", "kun", "di", "dao", "huo", "tao", "qi", "gu",
                    "guan", "zui", "ling", "lu", "bing", "jin", "dao", "zhi",
                    "lu", "shan,chan", "bei", "zhe", "hui", "you", "xi", "yin",
                    "zi", "huo", "zhen", "fu", "yuan", "wu", "xian", "yang",
                    "ti", "yi", "mei", "si", "di", "none", "zhuo", "zhen",
                    "yong", "ji", "gao", "tang", "chi", "ma", "ta", "none",
                    "xuan", "qi", "yu", "xi", "ji", "si", "chan,shan", "xuan",
                    "hui", "sui", "li", "nong", "ni,mi", "dao", "li", "rang",
                    "yue", "ti", "zan", "lei", "rou", "yu", "yu", "li", "xie",
                    "qin", "he", "tu", "xiu", "si", "ren", "tu", "zi", "cha",
                    "gan", "yi", "xian", "bing", "nian", "qiu", "qiu",
                    "zhong,chong", "fen", "hao", "yun", "ke", "miao", "zhi",
                    "jing", "bi", "zhi", "yu", "mi,bi,lin", "ku", "ban", "pi",
                    "ni", "li", "you", "zu", "pi", "ba", "ling", "mo", "cheng",
                    "nian", "qin", "yang", "zuo", "zhi", "zhi", "shu", "ju",
                    "zi", "tai", "ji", "cheng", "tong", "zhi", "huo", "he",
                    "yin", "zi", "zhi", "jie", "ren", "du", "yi", "zhu", "hui",
                    "nong", "fu", "xi", "kao", "lang", "fu", "ze", "shui",
                    "lu:", "kun", "gan", "jing", "ti", "cheng", "tu", "shao",
                    "shui", "ya", "lun", "lu", "gu", "zuo", "ren", "zhun",
                    "bang", "bai,bi", "ji,qi", "zhi", "zhi", "kun", "leng",
                    "peng", "ke", "bing", "chou", "zui", "yu", "su", "none",
                    "none", "yi", "xi", "bian", "ji", "fu", "bi", "nuo", "jie",
                    "zhong,chong", "zong", "xu", "cheng", "dao", "wen", "lian",
                    "zi", "yu", "ji", "xu", "zhen", "zhi", "dao", "jia",
                    "ji,qi", "gao", "gao", "gu", "rong", "sui", "none", "ji",
                    "kang", "mu", "shan", "men", "zhi", "ji", "lu", "su,wei",
                    "ji", "ying", "wen", "qiu", "se", "none", "yi", "huang",
                    "qie", "ji", "sui", "xiao", "pu", "jiao", "zhuo", "tong",
                    "none", "lu:", "sui", "nong", "se", "hui", "rang", "nuo",
                    "yu", "none", "ji", "tui", "wen", "cheng", "huo", "gong",
                    "lu:", "biao", "none", "rang", "jue", "li", "zan", "xue",
                    "wa", "jiu", "qiong", "xi", "qiong", "kong", "yu", "sen",
                    "jing", "yao", "chuan", "zhun", "tu", "lao", "qie",
                    "zhai,ze", "yao", "bian", "bao", "yao", "bing", "yu",
                    "zhu", "jiao", "qiao", "diao", "wu", "gui", "yao", "zhi",
                    "chuan", "yao", "tiao", "jiao", "chuang", "jiong,jun",
                    "xiao", "cheng", "kou", "cuan", "wo", "dan", "ku", "ke",
                    "zhui", "xu", "su", "none", "kui", "dou", "none",
                    "yin,xun", "wo", "wa", "ya", "yu", "ju", "qiong", "yao",
                    "yao", "tiao", "liao", "yu", "tian", "diao", "ju", "liao",
                    "xi", "wu", "kui", "chuang", "ju", "none", "kuan", "long",
                    "cheng", "cui", "piao", "zao", "cuan", "qiao", "qiong",
                    "dou", "zao", "zao", "qie", "li", "chu", "shi,gong,sheng",
                    "fu", "qian,gong,sheng", "chu", "hong", "qi,ji",
                    "qian,fen,zhi,yi,gong,sheng", "gong,sheng",
                    "shi,fen,zhi,yi,gong,sheng", "shu", "miao", "ju", "zhan",
                    "zhu", "ling", "long", "bing", "jing", "jing", "zhang",
                    "yi,gong,sheng,bai,bei,si", "si,qi", "jun", "hong", "tong",
                    "song", "jing", "diao", "yi", "shu", "jing", "qu", "jie",
                    "ping", "duan", "shao", "zhuan", "ceng", "deng", "cun",
                    "huai", "jing", "kan", "jing", "zhu", "zhu", "le", "peng",
                    "yu", "chi", "gan", "mang", "zhu", "none", "du", "ji",
                    "xiao", "ba", "suan", "ji", "zhen", "zhao", "sun", "ya",
                    "zhui", "yuan", "hu", "gang", "xiao", "cen", "pi", "bi",
                    "jian", "yi", "dong", "shan", "sheng", "xia", "di", "zhu",
                    "na", "chi", "gu", "li", "qie", "min", "bao", "tiao", "si",
                    "fu", "ce", "ben", "fa", "da", "zi", "di", "ling",
                    "ze,zuo", "nu", "fu", "gou", "fan", "jia", "ge", "fan",
                    "shi", "mao", "po", "none", "jian", "qiong", "long",
                    "none", "bian", "luo", "gui", "qu", "chi", "yin", "yao",
                    "xian", "bi", "qiong", "gua", "deng", "jiao", "jin",
                    "quan", "sun", "ru", "fa", "kuang", "zhu", "tong", "ji",
                    "da", "hang", "ce", "zhong", "kou", "lai", "bi", "shai",
                    "dang", "zheng", "ce", "fu", "yun,jun", "tu", "pa", "li",
                    "lang", "ju", "guan", "jian", "han", "tong", "xia", "zhi",
                    "cheng", "suan", "shi", "zhu", "zuo", "xiao", "shao",
                    "ting", "jia,ce", "yan", "gao", "kuai", "gan", "chou",
                    "kuang", "gang", "yun", "none", "qian", "xiao", "jian",
                    "pu", "lai", "zou", "bi", "bi", "bi", "ge", "chi", "guai",
                    "yu", "jian", "zhao", "gu", "chi", "zheng", "qing", "sha",
                    "zhou", "lu", "bo", "ji", "lin", "suan", "jun", "fu",
                    "zha", "gu", "kong", "qian", "qian", "jun", "chui", "guan",
                    "yuan", "ce", "ju", "bo", "ze", "qie", "tuo", "luo", "dan",
                    "xiao", "ruo", "jian", "none", "bian", "sun", "xiang",
                    "xian", "ping", "zhen", "sheng", "hu", "shi,yi", "zhu",
                    "yue", "chun", "fu", "wu", "dong", "shuo", "ji", "jie",
                    "huang", "xing", "mei", "fan", "chuan", "zhuan", "pian",
                    "feng", "zhu", "hong", "qie", "hou", "qiu", "miao", "qian",
                    "none", "kui", "none", "lou", "yun", "he", "tang", "yue",
                    "chou", "gao", "fei", "ruo", "zheng", "gou", "nie", "qian",
                    "xiao", "cuan", "gong", "pang", "du", "li", "bi", "zhuo",
                    "chu", "shai", "chi", "zhu", "qiang", "long", "lan",
                    "jian", "bu", "li", "hui", "bi", "di", "cong", "yan",
                    "peng", "sen", "cuan", "pai", "piao", "dou", "yu", "mie",
                    "zhuan", "ze,kui", "xi", "guo", "yi", "hu", "chan", "kou",
                    "cu", "ping", "zao", "ji", "gui", "su", "lou", "zha", "lu",
                    "nian", "suo", "cuan", "none", "suo", "le", "duan",
                    "liang", "xiao", "bo", "mi", "shai", "dang", "liao", "dan",
                    "dian", "fu", "jian", "min", "kui", "dai", "qiao", "deng",
                    "huang", "sun", "lao", "zan", "xiao", "lu", "shi", "zan",
                    "none", "pai", "qi", "pai", "gan", "ju", "du", "lu", "yan",
                    "bo", "dang", "sai", "ke", "gou", "qian", "lian", "bu",
                    "zhou", "lai", "none", "lan", "kui", "yu", "yue", "hao",
                    "zhen", "tai", "ti", "mi", "chou", "ji", "none", "qi",
                    "teng", "zhuan", "zhou", "fan", "sou", "zhou", "qian",
                    "kuo", "teng", "lu", "lu", "jian", "tuo", "ying", "yu",
                    "lai", "long", "none", "lian", "lan", "qian", "yue",
                    "zhong", "qu", "lian", "bian", "duan", "zuan", "li",
                    "shai", "luo", "ying", "yue", "zhuo", "xu,yu", "mi", "di",
                    "fan", "shen", "zhe", "shen", "nu:", "xie", "lei", "xian",
                    "zi", "ni", "cun", "zhang", "qian", "none", "bi", "ban",
                    "wu", "sha", "kang", "rou", "fen", "bi", "cui,sui", "yin",
                    "li", "chi", "tai", "none", "ba", "li", "gan", "ju", "po",
                    "mo", "cu", "zhan,nian", "zhou", "li", "su", "tiao", "li",
                    "xi", "su", "hong", "tong", "zi,ci", "ce", "yue",
                    "zhou,yu", "lin", "zhuang", "bai", "none", "fen", "mian",
                    "qu", "none", "liang", "xian", "fu", "liang", "can",
                    "jing,geng", "li", "yue", "lu", "ju", "qi", "cui", "bai",
                    "chang", "lin", "zong", "jing", "guo", "none", "san,shen",
                    "san,shen", "tang", "bian", "rou", "mian", "hou", "xu",
                    "zong", "hu", "jian", "zan", "ci", "li", "xie", "fu",
                    "nuo", "bei", "gu,yu", "xiu", "gao", "tang", "qiu", "none",
                    "cao", "zhuang", "tang", "mi,mei", "san,shen", "fen",
                    "zao", "kang", "jiang", "mo", "san", "san", "nuo", "chi",
                    "liang", "jiang", "kuai", "bo", "huan", "shu", "zong",
                    "jian", "nuo", "tuan", "nie", "li", "zuo", "di", "nie",
                    "tiao", "lan", "mi", "mi", "jiu", "xi,ji", "gong", "zheng",
                    "jiu", "you", "ji", "cha", "zhou", "xun", "yue,yao",
                    "hong,gong", "yu", "he,ge", "wan", "ren", "wen", "wen",
                    "qiu", "na", "zi", "tou", "niu", "fou", "jie", "shu",
                    "chun", "pi", "yin", "sha", "hong", "zhi", "ji", "fen",
                    "yun", "ren", "dan", "jin", "su", "fang", "suo", "cui",
                    "jiu", "zha", "ba", "jin", "fu", "zhi", "qi", "zi", "chou",
                    "hong", "zha,za", "lei", "xi", "fu", "xie", "shen", "bei",
                    "zhu", "qu", "ling", "zhu", "shao", "gan", "yang", "fu",
                    "tuo", "zhen", "dai", "chu", "shi", "zhong", "xian", "zu",
                    "jiong", "ban", "ju", "pa", "shu", "zui", "kuang", "jing",
                    "ren", "heng,hang", "xie", "jie", "zhu", "chou", "gua",
                    "bai", "jue", "kuang", "hu", "ci", "geng", "geng", "tao",
                    "xie,jie", "ku", "jiao", "quan", "gai", "luo,lao", "xuan",
                    "beng,ping", "xian", "fu", "gei,ji", "tong", "rong",
                    "tiao", "yin", "lei", "xie", "quan", "xu", "hai", "die",
                    "tong", "si", "jiang", "xiang", "hui", "jue", "zhi",
                    "jian", "juan", "chi", "mian", "zhen", "lu:", "cheng",
                    "qiu", "shu", "bang", "tong", "xiao", "wan", "qin", "geng",
                    "xiu", "ti,di", "xiu", "xie", "hong", "xi", "fu", "ting",
                    "sui", "dui", "kun", "fu", "jing", "hu", "zhi", "yan",
                    "jiong", "feng", "ji", "xu", "none", "zong,zeng", "lin",
                    "duo", "li", "lu:", "liang", "chou", "quan", "shao", "qi",
                    "qi", "zhun", "qi", "wan", "qian", "xian", "shou", "wei",
                    "qi,qing", "tao", "wan", "gang", "wang", "beng", "zhui",
                    "cai", "guo", "cui", "lun,guan", "liu", "qi", "zhan",
                    "bei", "chuo", "ling", "mian", "qi", "jie", "tan", "zong",
                    "gun", "zou", "yi", "zi", "xing", "liang", "jin", "fei",
                    "rui", "min", "yu", "zong", "fan", "lu:", "xu", "none",
                    "shang", "none", "xu", "xiang", "jian", "ke", "xian",
                    "ruan", "mian", "ji,qi", "duan", "zhong", "di", "min",
                    "miao", "yuan", "xie", "bao", "si", "qiu", "bian", "huan",
                    "geng", "zong", "mian", "wei", "fu", "wei", "yu", "gou",
                    "miao", "jie", "lian", "zong", "bian,pian", "yun", "yin",
                    "ti", "gua", "zhi", "yun", "cheng", "chan", "dai", "jia",
                    "yuan", "zong", "xu", "sheng", "none", "geng", "none",
                    "ying", "jin", "yi", "zhui", "ni", "bang", "gu", "pan",
                    "zhou", "jian", "cuo", "quan", "shuang", "yun", "xia",
                    "shuai", "xi", "rong", "tao", "fu", "yun", "zhen", "gao",
                    "ru", "hu", "zai", "teng", "xian,xuan", "su", "zhen",
                    "zong", "tao", "huang", "cai", "bi,bie", "feng", "cu",
                    "li", "suo", "yin", "xi", "zong", "lei", "zhuan", "qian",
                    "man", "zhi", "lu:", "mo", "piao", "lian", "mi", "xuan",
                    "zong", "ji", "shan", "sui", "fan,po", "shuai", "beng",
                    "yi", "sao", "mou,miao,miu", "zhou,yao,you", "qiang",
                    "hun", "xian", "xi,ji", "none", "xiu", "ran", "xuan",
                    "hui", "qiao", "zeng", "zuo", "zhi", "shan", "san", "lin",
                    "yu", "fan", "liao", "chuo", "zun", "jian", "rao", "chan",
                    "rui", "xiu", "hui", "hua", "zuan", "xi", "qiang", "none",
                    "da", "sheng", "hui", "xi,ji", "se", "jian", "jiang",
                    "huan", "qiao,zao", "cong", "jie", "jiao,zhuo", "bo",
                    "chan", "yi", "nao", "sui", "yi", "shai", "xu", "ji",
                    "bin", "qian", "jian,kan", "pu", "xun", "zuan", "qi",
                    "peng", "li", "mo", "lei", "xie", "zuan", "kuang", "you",
                    "xu", "lei", "xian", "chan", "none", "lu", "chan", "ying",
                    "cai", "xiang", "xian", "zui", "zuan", "luo", "xi",
                    "dao,du", "lan", "lei", "lian", "mi", "jiu", "yu",
                    "hong,gong", "zhou", "xian,qian", "he,ge", "yue,yao", "ji",
                    "wan", "kuang", "ji", "ren", "wei", "yun", "hong", "chun",
                    "pi", "sha", "gang", "na", "ren", "zong", "lun,guan",
                    "fen", "zhi", "wen", "fang", "zhu", "zhen", "niu", "shu",
                    "xian", "gan", "xie", "fu", "lian", "zu", "shen", "xi",
                    "zhi", "zhong", "zhou", "ban", "fu", "chu", "shao", "yi",
                    "jing", "dai", "bang", "rong", "jie", "ku", "rao", "die",
                    "hang", "hui", "ji,gei", "xuan", "jiang", "luo,lao", "jue",
                    "jiao", "tong", "geng", "xiao", "juan", "xiu", "xi", "sui",
                    "tao", "ji", "ti,di", "ji", "xu", "ling", "yin", "xu",
                    "qi", "fei", "chuo,chao", "shang", "gun", "sheng", "wei",
                    "mian", "shou", "beng", "chou", "tao", "liu", "quan",
                    "zong,zeng", "zhan", "wan", "lu:", "zhui", "zi", "ke",
                    "xiang", "jian", "mian", "lan", "ti", "miao", "ji,qi",
                    "yun", "hui", "si", "duo", "duan", "bian,pian", "xian",
                    "gou", "zhui", "huan", "di", "lu:", "bian", "min", "yuan",
                    "jin", "fu", "ru", "zhen", "feng", "cui", "gao", "chan",
                    "li", "yi", "jian", "bin", "piao", "man", "lei", "ying",
                    "suo", "mou,miao,miu", "sao", "xie", "liao", "shan",
                    "zeng", "jiang", "qian", "qiao,sao,zao", "huan",
                    "jiao,zhuo", "zuan", "fou"
            };
        }
    }
}
