
package cn.com.nd.momo.api.util;

/**
 * 多音节，从0x4e07到0x5E66
 * 
 * @author chenjp
 */
public class MultiPinYin1 {
    public static String[] pinyinArray = null;

    private MultiPinYin1() {
    };

    static {
        if (null == pinyinArray) {
            pinyinArray = new String[] {
                    "yi", "ding,zheng", "kao", "qi",
                    "shang", "xia", "none", "wan,mo", "zhang", "san", "shang",
                    "xia", "ji", "bu,fou", "yu", "mian", "gai", "chou", "chou",
                    "zhuan", "qie,ju", "pi", "shi", "shi", "qiu", "bing", "ye",
                    "cong", "dong", "si", "cheng", "diu", "qiu", "liang",
                    "diu", "you", "liang", "yan", "bing", "sang", "shu", "jiu",
                    "ge", "ya", "qiang,pan", "zhong", "ji", "jie", "feng",
                    "guan", "chuan", "chan", "lin", "zhuo", "zhu,dian", "none",
                    "wan", "dan", "wei", "zhu", "jing,dan", "li", "ju", "pie",
                    "fu", "yi", "yi,ai", "nai", "none", "jiu", "jiu", "tuo",
                    "me,ma,yao", "yi", "none", "zhi", "wu", "zha", "hu", "fa",
                    "le,yue", "zhong", "ping", "pang", "qiao", "hu", "guai",
                    "cheng,sheng", "cheng,sheng", "yi", "yin", "none",
                    "mie,nie", "jiu", "qi", "ye", "xi", "xiang", "gai", "diu",
                    "none", "none", "shu", "none", "shi", "ji", "nang", "jia",
                    "none", "shi", "none", "none", "mai", "luan", "none", "ru",
                    "xi", "yan", "fu", "sha", "na", "gan,qian", "none", "none",
                    "none", "none", "qian,gan", "zhi", "gui,jun,qiu", "gan",
                    "luan", "lin", "yi", "jue", "le,liao", "none", "yu",
                    "zheng", "shi", "shi", "er", "chu", "yu", "kui", "yu",
                    "yun", "hu", "qi", "wu", "jing", "si", "sui", "gen",
                    "gen,geng", "ya", "xie", "ya", "qi", "ya", "ji,qi", "tou",
                    "wang,wu", "kang", "ta", "jiao", "hai", "yi", "chan",
                    "heng", "mu", "none", "xiang", "jing", "ting", "liang",
                    "heng", "jing", "ye", "qin,qing", "bo", "you", "xie",
                    "dan", "lian", "duo", "wei", "ren", "ren", "ji", "none",
                    "wang", "yi", "shen,shi", "ren", "le", "ding", "ze", "jin",
                    "pu", "chou,qiu", "ba", "zhang", "jin", "jie", "bing",
                    "reng", "cong", "fo,fu", "san", "lun", "none", "cang",
                    "zi,zai", "shi", "ta", "zhang", "fu", "xian", "xian",
                    "cha", "hong", "tong", "ren", "qian", "gan", "ge,yi", "di",
                    "dai", "ling", "yi", "chao", "chang", "sa", "shang", "yi",
                    "mu", "men", "ren", "jia", "chao", "yang", "qian", "zhong",
                    "pi", "wan", "wu", "jian", "jia,jie", "yao", "feng",
                    "cang", "ren", "wang", "fen", "di", "fang", "zhong", "qi",
                    "pei", "yu", "diao", "dun", "wen", "yi", "xin", "kang",
                    "yi", "ji", "ai", "wu", "ji", "fu", "fa", "xiu", "jin",
                    "bei", "chen", "fu", "tang", "zhong", "you", "huo",
                    "hui,kuai", "yu", "cui,zu", "yun", "san", "wei",
                    "chuan,zhuan", "che", "ya", "xian", "shang", "chang,tang",
                    "lun", "cang,chen", "xun", "xin", "wei", "zhu", "chi",
                    "xuan", "nao,nu", "bo,bai", "gu", "ni", "ni", "xie", "ban",
                    "xu", "ling", "zhou", "shen", "qu", "si,ci", "beng",
                    "si,shi", "jia,ga,qie,qia", "pi", "yi", "si,shi", "ai",
                    "zheng", "dian,tian", "han", "mai", "dan", "zhu", "bu",
                    "qu", "bi", "shao", "ci", "wei", "di", "zhu", "zuo", "you",
                    "yang", "ti,ben", "zhan", "he", "bi", "tuo", "she",
                    "yu,tu", "yi,die", "fo,fu", "zuo", "gou", "ning", "tong",
                    "ni", "xuan,san", "ju", "yong", "wa", "qian", "none", "ka",
                    "none", "pei", "huai", "he", "lao", "xiang", "ge", "yang",
                    "bai", "fa", "ming", "jia", "nai,er", "bing", "ji", "heng",
                    "huo", "gui", "quan", "tiao", "jiao", "ci", "yi", "shi",
                    "xing", "shen", "tuo", "kan", "zhi", "gai,kai", "lai",
                    "yi", "chi", "kua", "guang", "li", "yin", "shi", "mi",
                    "zhu", "xu", "you", "an", "lu", "mou", "er", "lun",
                    "dong,tong", "cha", "chi", "xun", "gong", "zhou", "yi",
                    "ru", "jian", "xia", "jia,jie", "zai", "lu:", "none",
                    "jiao,yao", "zhen", "ce,ze,zhai", "qiao", "kuai", "chai",
                    "ning", "nong", "jin", "wu", "hou", "jiong", "cheng",
                    "zhen", "cuo", "chou", "qin", "lu:", "ju", "shu", "ting",
                    "shen", "tuo", "bo", "nan", "hao", "bian,pian", "tui",
                    "yu", "xi", "cu", "e", "qiu", "xu", "kuang", "ku", "wu",
                    "jun,zun,juan", "yi", "fu", "lang", "zu", "qiao", "li",
                    "yong", "hun", "jing", "xian", "san", "pai", "su", "fu",
                    "xi", "li", "mian", "ping", "bao", "yu,shu", "si,qi",
                    "xia", "xin,shen", "xiu", "yu", "di", "che", "chou",
                    "none", "yan", "liang", "li", "lai", "si", "jian", "xiu",
                    "fu", "he", "ju", "xiao", "pai", "jian", "biao", "ti,chu",
                    "fei", "feng", "ya", "an", "bei", "yu,zhou", "xin",
                    "bi,bei", "chi", "chang", "zhi", "bing", "zan", "yao",
                    "cui", "lia,liang", "wan", "lai", "cang", "zong", "ge",
                    "guan", "bei", "tian", "shu", "shu", "men", "dao", "tan",
                    "jue", "chui", "xing", "peng", "tang,chang", "hou", "yi",
                    "qi", "ti", "gan", "jing,liang", "jie", "xu", "chang",
                    "jie", "fang", "zhi", "kong", "juan", "zong", "ju", "qian",
                    "ni", "lun", "zhuo", "wo", "luo", "song", "leng", "hun",
                    "dong", "zi", "ben", "wu", "ju", "nai", "cai", "jian",
                    "zhai", "ye", "zhi", "sha", "qing", "none", "ying",
                    "cheng", "qian", "yan", "nuan", "zhong", "chun", "jia",
                    "jie", "wei", "yu", "bing", "ruo", "ti", "wei", "pian",
                    "yan", "feng", "tang", "wo", "e", "xie,jie", "che",
                    "sheng", "kan", "di", "zuo", "cha", "ting", "bei", "ye",
                    "huang", "yao", "zhan", "qiu", "yan", "you", "jian", "xu",
                    "zha", "chai", "fu", "bi", "zhi", "zong", "mian", "ji",
                    "yi", "xie", "xun", "si,cai", "duan", "ce,ze", "zhen",
                    "ou", "tou", "tou", "bei", "za,zan", "lou,lu:", "jie",
                    "wei", "fen", "chang", "kui,gui", "sou", "chi", "su",
                    "xia", "fu", "yuan", "rong", "li", "ru", "yun", "gou",
                    "ma", "bang", "dian", "tang", "hao", "jie", "xi", "shan",
                    "qian", "jue", "cang", "chu", "san", "bei", "xiao", "yong",
                    "yao", "ta", "suo", "wang", "fa", "bing", "jia", "dai",
                    "zai", "tang", "none", "bin", "chu", "nuo", "zan", "lei",
                    "cui", "yong", "zao", "zong", "peng", "song", "ao",
                    "chuan,zhuan", "yu", "zhai", "zu", "shang", "qiang",
                    "qiang", "chi", "sha", "han", "zhang", "qing", "yan", "di",
                    "xi", "lou,lu:", "bei", "piao", "jin", "lian", "lu", "man",
                    "qian", "xian", "qiu", "ying", "dong", "zhuan", "xiang",
                    "shan", "qiao", "jiong", "tui", "zun", "pu", "xi", "lao",
                    "chang", "guang", "liao", "qi", "deng", "chan", "wei",
                    "zhang", "fan", "hui", "chuan", "tie", "dan", "jiao,yao",
                    "jiu", "seng", "fen", "xian", "jue", "e", "jiao", "jian",
                    "tong,zhuang", "lin", "bo", "gu", "xian", "su", "xian",
                    "jiang", "min", "ye", "jin", "jia", "qiao", "pi", "feng",
                    "zhou", "ai", "sai", "yi", "jun,juan", "nong", "shan",
                    "yi", "dang", "jing", "xuan", "kuai", "jian", "chu", "dan",
                    "jiao", "sha", "zai", "none", "bin", "an", "ru", "tai",
                    "chou", "chai", "lan", "ni", "jin", "qian", "meng", "wu",
                    "neng", "qiong", "ni", "chang", "lie", "lei", "lu:",
                    "kuang", "bao", "du", "biao", "zan", "zhi", "si", "you",
                    "hao", "qin", "chen", "li", "teng", "wei", "long", "chu",
                    "chan", "rang", "shu", "hui", "li", "luo", "zan,zuan",
                    "nuo", "tang", "yan", "lei", "nang", "er", "wu", "yun",
                    "zan", "yuan", "xiong", "chong", "zhao", "xiong", "xian",
                    "guang", "dui", "ke", "dui", "mian,wen", "tu",
                    "chang,zhang", "er", "dui", "er", "jin", "tu", "si", "yan",
                    "yan", "shi", "shi,ke", "dang", "qian", "dou", "fen",
                    "mao", "xin", "dou", "bai,ke", "jing", "li", "kuang", "ru",
                    "wang,wu", "nei", "quan", "liang", "yu,shu", "ba", "gong",
                    "liu,lu", "xi", "none", "lan", "gong", "tian", "guan",
                    "xing", "bing", "qi,ji", "ju", "dian", "zi,ci", "none",
                    "yang", "jian", "shou", "ji", "yi", "ji", "chan", "jiong",
                    "mao", "ran", "nei", "yuan", "mao,mou", "gang", "ran",
                    "ce", "jiong", "ce", "zai", "gua", "jiong", "mao,mo",
                    "zhou", "mao,mo", "gou", "xu", "mian", "mi", "rong", "yin",
                    "xie", "kan", "jun", "nong", "yi", "mi", "shi", "guan",
                    "meng", "zhong", "zui", "yuan", "ming", "kou", "none",
                    "fu", "xie", "mi", "bing", "dong", "tai", "gang",
                    "feng,ping", "bing", "hu", "chong", "jue", "hu", "kuang",
                    "ye", "leng", "pan", "fu", "min", "dong", "xian", "lie",
                    "xia", "jian", "jing", "shu", "mei", "shang", "qi", "gu",
                    "zhun", "song", "jing", "liang", "qing,jing", "diao",
                    "ling", "dong", "gan", "jian", "yin", "cou", "ai", "li",
                    "cang", "ming", "zhun", "cui", "si", "duo", "jin", "lin",
                    "lin", "ning", "xi", "du", "ji", "fan", "fan", "fan",
                    "feng", "ju", "chu", "none", "feng", "none", "none", "fu",
                    "feng", "ping", "feng", "kai", "huang", "kai", "gan",
                    "deng", "ping", "qu,kan", "xiong", "kuai", "tu,gu",
                    "ao,wa", "chu", "ji", "dang", "han", "han", "zao,zuo",
                    "dao", "diao", "dao", "ren", "ren", "chuang", "fen", "qie",
                    "yi", "ji", "kan", "qian", "cun", "chu", "wen", "ji",
                    "dan", "xing", "hua,huai", "wan", "jue", "li", "yue",
                    "lie", "liu", "ze", "gang", "chuang", "fu", "chu", "qu",
                    "ju", "shan", "min", "ling", "zhong", "pan", "bie", "jie",
                    "jie", "bao,pao", "li", "shan", "bie", "chan", "jing",
                    "gua", "gen", "dao", "chuang", "kui", "ku", "duo", "er",
                    "zhi", "shua", "quan,xuan", "cha,sha", "ci", "ke", "jie",
                    "gui", "ci", "gui", "kai", "duo", "ji", "ti", "jing",
                    "lou", "luo", "ze", "yuan", "cuo", "xue,xiao", "ke", "la",
                    "qian", "cha", "chuan", "gua", "jian", "cuo", "li", "ti",
                    "fei", "pou", "chan", "qi", "chuang", "zi", "gang", "wan",
                    "bo", "ji", "duo", "qing", "yan,shan", "zhuo", "jian",
                    "ji", "bo,bao", "yan", "ju", "huo", "sheng", "jian", "duo",
                    "duan", "wu", "gua", "fu", "sheng", "jian", "ge", "zha",
                    "kai", "chuang", "juan", "chan", "tuan,zhuan", "lu", "li",
                    "fou", "shan", "piao", "kou", "jiao,chao", "gua", "qiao",
                    "jue", "hua", "zha", "zhuo", "lian", "ju", "pi", "liu",
                    "gui", "jiao", "gui", "jian", "jian", "tang", "huo", "ji",
                    "jian", "yi", "jian", "zhi", "chan", "cuan", "mo", "li",
                    "zhu", "li", "ya", "quan", "ban", "gong", "jia", "wu",
                    "mai", "lie", "jing", "keng", "xie", "zhi", "dong", "zhu",
                    "nu,nao", "jie", "qu", "shao", "yi", "zhu", "mo", "li",
                    "jing", "lao", "lao", "juan", "kou", "yang", "wa", "xiao",
                    "mou", "kuang", "jie", "lie", "he", "shi", "ke", "jing",
                    "hao", "bo", "min", "chi", "lang", "yong", "yong", "mian",
                    "ke", "xun", "juan", "qing", "lu", "bu", "meng", "lai",
                    "le,lei", "kai", "mian", "dong", "xu", "xu", "kan", "wu",
                    "yi", "xun", "weng", "sheng", "lao", "mu", "lu", "piao",
                    "shi", "ji", "qin", "qiang", "jiao,chao", "quan", "xiang",
                    "yi", "qiao", "fan", "juan", "tong", "ju", "dan", "xie",
                    "mai", "xun", "xun", "lu:", "li", "che", "rang", "quan",
                    "bao", "shao,shuo,biao", "yun", "jiu", "bao", "gou", "wu",
                    "yun", "none", "none", "gai", "gai", "bao", "cong", "none",
                    "xiong", "peng", "ju", "tao", "ge", "pu", "an", "pao",
                    "fu", "gong", "da", "jiu", "qiong", "bi", "hua", "bei",
                    "nao", "chi,shi", "fang,xi", "jiu", "yi", "za", "jiang",
                    "kang", "jiang", "kuang", "hu", "xia", "qu", "fan", "gui",
                    "qie", "cang,zang", "kuang", "fei", "hu", "yu", "gui",
                    "kui", "hui", "dan", "kui", "lian", "lian", "suan", "du",
                    "jiu", "qu", "xi", "pi,ya", "qu,ou", "yi", "an", "yan",
                    "bian", "ni", "qu,ou", "shi", "xin", "qian", "nian", "sa",
                    "zu", "sheng", "wu", "hui", "ban", "shi", "xi", "wan",
                    "hua", "xie", "wan", "bei", "zu,cu", "zhuo", "xie",
                    "dan,chan,shan", "mai", "nan", "dan,chan", "ji", "bo",
                    "shuai,lu:", "bu,bo", "kuang", "bian", "bu", "zhan",
                    "ka,qia", "lu", "you", "lu", "xi", "gua", "wo", "xie",
                    "jie", "jie", "wei", "ang,yang", "qiong", "zhi", "mao",
                    "yin", "wei", "shao", "ji", "que", "luan", "shi",
                    "juan,quan", "xie", "xu", "jin", "que", "wu", "ji", "e",
                    "qing", "xi", "none", "chang", "han", "e", "ting", "li",
                    "zhe", "an,chang", "li", "ya", "ya", "yan", "she", "zhi",
                    "zha", "pang", "none", "ke", "ya", "zhi", "ce,si", "pang",
                    "ti", "li", "she", "hou", "ting", "zui", "cuo", "fei",
                    "yuan", "ce,si", "yuan", "xiang", "yan", "li", "jue",
                    "sha,xia", "dian", "chu", "jiu", "qin,jin", "ao", "gui",
                    "yan", "si", "li", "chang", "lan", "li", "yan", "yan",
                    "yuan", "si", "si", "lin", "qiu", "qu", "qu", "none",
                    "lei", "du", "xian", "zhuan", "san", "can,cen,shen",
                    "can,cen,shen,san", "san", "can,cen,shen", "ai", "dai",
                    "you", "cha", "ji", "you", "shuang", "fan", "shou", "guai",
                    "ba", "fa", "ruo", "shi", "shu", "zhui", "qu", "shou",
                    "bian", "xu", "jia", "pan", "sou", "ji", "yu", "sou",
                    "die", "rui", "cong", "kou", "gu", "ju,gou", "ling", "gua",
                    "tao,dao", "kou", "zhi", "jiao", "zhao,shao", "ba", "ding",
                    "ke", "tai", "chi", "shi", "you", "qiu", "po", "ye,xie",
                    "hao", "si", "tan", "chi", "le", "diao", "ji", "none",
                    "hong", "mie", "yu,xu", "mang", "chi,ji", "ge", "xuan",
                    "yao", "zi", "he,ge", "ji", "diao", "cun", "tong", "ming",
                    "hou", "li", "tu", "xiang", "zha", "he,xia", "ye", "lu:",
                    "a", "ma", "ou", "xue", "yi", "jun", "chou", "lin", "tun",
                    "yin", "fei", "bi,pi", "qin", "qin", "jie", "pou",
                    "fou,pi", "ba", "dun", "fen", "e", "han", "ting,yin",
                    "hang,keng", "shun", "qi", "hu", "zhi,zi", "yin", "wu",
                    "wu", "chao", "na", "chuo", "xi", "chui", "dou", "wen",
                    "hou", "ou,hong", "wu", "gao,gu", "ya", "jun", "lu:", "e",
                    "ge", "mei", "dai", "qi", "cheng", "wu", "gao,gu", "fu",
                    "jiao", "hong", "chi", "sheng", "na,ne", "tun", "m", "yi",
                    "dai,tai", "ou", "li", "bei,bai", "yuan,yun", "guo",
                    "none", "qiang", "wu", "e", "shi", "quan", "pen", "wen",
                    "ni,ne,na", "mou", "ling", "ran", "you", "di", "zhou",
                    "shi", "zhou", "zhan", "ling", "yi", "qi", "ping", "zi",
                    "gua,wa", "ci,zi", "wei", "xu", "he,ke,a", "nao", "xia",
                    "pei", "yi", "xiao", "shen", "hu", "ming", "da", "qu",
                    "ju,zui", "gan", "za", "tuo", "duo", "pou", "pao", "bie",
                    "fu", "bi,fu", "he,huo", "za,ze,zha", "he,huo,hai", "hai",
                    "jiu", "yong", "fu", "da", "zhou", "wa", "ka", "gu",
                    "ka,ga", "zuo", "bu", "long", "dong", "ning", "zha", "si",
                    "xian", "huo", "qi", "er", "e", "guang", "zha", "xi,die",
                    "yi", "lie", "zi", "mie", "mi", "zhi", "yao", "ji", "zhou",
                    "ge,ka,lo,luo", "shuai", "zan", "xiao", "ke,hai,ka,kai",
                    "hui", "kua", "huai", "tao", "xian", "e", "xuan", "xiu",
                    "guo,kuai", "yan,ye", "lao", "yi", "ai", "pin", "shen",
                    "tong", "hong", "xiong,hong", "duo", "wa", "ha,ka", "zai",
                    "you", "di", "pai", "xiang", "ai", "gen", "kuang", "ya",
                    "da", "xiao", "bi", "hui,yue", "none", "hua,ye", "none",
                    "kuai", "duo", "none", "ji", "nong", "mou", "yo", "hao",
                    "yuan,yun", "long", "pou", "mang", "ge", "e,o,wo", "chi",
                    "shao", "li", "na,nei,nai", "zu", "he", "ku", "xiao",
                    "xian", "lao", "bei", "zhe", "zha", "liang", "ba", "mi",
                    "le", "sui", "fou", "bu", "han", "heng,hng", "geng",
                    "shuo", "ge", "you", "yan", "gu", "gu", "bai,bei", "han",
                    "suo", "chun", "yi", "ai", "jia", "tu", "xian", "guan",
                    "li", "xi", "tang", "zuo", "miu", "che", "wu,n,ng", "zao",
                    "ya", "dou", "qi", "di", "qin", "ma", "none", "gong",
                    "dou", "none", "lao", "liang", "suo", "zao", "huan",
                    "none", "gou", "ji", "zuo", "wo", "feng", "yin", "hu,xia",
                    "qi", "shou", "wei", "shua", "chang", "er", "li", "qiang",
                    "an", "jie", "yo", "nian", "yu", "tian", "lai", "sha",
                    "xi", "tuo", "hu", "ai", "zhou,zhao", "nou", "ken", "zhuo",
                    "zhuo", "shang", "di", "heng", "lin", "a", "xiao", "xiang",
                    "tun", "wu", "wen", "cui", "jie", "hu", "qi", "qi", "tao",
                    "dan", "dan", "wan", "zi", "bi", "cui", "chuo,chuai", "he",
                    "ya", "qi", "zhe", "fei", "liang", "xian", "pi", "sha",
                    "la", "ze", "qing", "gua", "pa", "zhe", "se", "zhuan",
                    "nie", "guo", "luo", "yan", "di", "quan", "tan,chan", "bo",
                    "ding", "lang", "xiao", "none", "tang", "chi", "ti", "an",
                    "jiu", "dan", "ka,ke", "yong", "wei", "nan", "shan", "yu",
                    "zhe", "la", "jie", "hou", "han", "die,zha", "zhou",
                    "chai", "kuai", "re,nuo", "yu", "yin", "zan", "yao", "wo",
                    "mian", "hu", "yun", "chuan", "hui", "huan", "huan", "xi",
                    "he", "ji", "kui", "zhong", "wei", "sha", "xu", "huang",
                    "du", "nie", "xuan", "liang", "yu", "sang", "chi", "qiao",
                    "yan", "dan,chan,shan", "pen", "shi,si", "li", "yo",
                    "zha,cha", "wei", "miao", "ying", "pen", "none", "kui",
                    "xi", "yu", "jie", "lou", "ku", "cao", "huo", "ti", "yao",
                    "he", "a,sha", "xiu", "qiang", "se", "yong", "su", "hong",
                    "xie", "ai,yi", "suo", "ma", "cha", "hai", "ke", "da,ta",
                    "sang", "chen", "ru,nou", "sou", "gong", "ji", "pang",
                    "wu", "qian", "shi", "ge", "zi", "jie,jue", "luo", "weng",
                    "wa", "si", "chi", "hao", "suo", "jia,lun", "hai,hei",
                    "suo", "qin", "nie", "he", "none", "sai", "ng", "ge", "na",
                    "dia", "ai", "none", "tong", "bi", "ao", "ao", "lian",
                    "cui", "zhe", "mo", "sou", "sou,zu", "tan", "di", "qi",
                    "jiao", "chong", "jiao", "kai", "tan", "san", "cao", "jia",
                    "none", "xiao", "piao", "lou", "ga", "gu,jia", "xiao",
                    "hu", "hui", "guo", "ou", "xian", "ze", "chang", "xu,shi",
                    "po", "de,dei", "ma", "ma,mo", "hu", "lei", "du", "ga",
                    "tang", "ye", "beng", "ying", "none", "jiao", "mi", "xiao",
                    "hua,ye", "mai", "ran", "zuo,chuai,zhuai", "peng", "lao",
                    "xiao", "ji", "zhu", "chao,zhao", "kui", "zui", "xiao",
                    "si", "hao", "fu,m", "liao", "qiao", "xi", "xu", "chan",
                    "dan", "hei,mo,hai", "xun", "wu", "zun", "pan", "chi",
                    "kui", "can", "zan", "cu", "dan", "yu", "tun",
                    "cheng,ceng", "jiao", "ye", "xi", "qi", "hao", "lian",
                    "xu,shi", "deng", "hui", "yin", "pu", "jue", "qin", "xun",
                    "nie", "lu", "si", "yan", "ying", "da", "zhan", "o",
                    "zhou", "jin", "nong", "hui,yue", "hui", "qi", "e", "zao",
                    "yi", "shi", "jiao", "yuan", "ai", "yong", "xue,jue",
                    "kuai", "yu", "pen", "dao", "ga", "xin", "dun", "dang",
                    "none", "sai", "pi", "pi", "yin", "zui", "ning", "di",
                    "han", "ta", "huo", "ru", "hao", "xia,he", "yan", "duo",
                    "pi", "chou", "ji", "jin", "hao", "ti", "chang", "none",
                    "none", "ca,cha", "ti", "lu", "hui", "bao", "you", "nie",
                    "yin", "hu", "mo", "huang", "zhe", "li", "liu", "none",
                    "nang", "xiao", "mo", "yan", "li", "lu", "long", "mo",
                    "dan", "chen", "pin", "pi", "xiang", "huo", "mo", "xi",
                    "duo", "ku", "yan", "chan", "ying", "rang", "dian", "la",
                    "ta", "xiao", "jiao,jue", "chuo", "huan", "huo", "zhuan",
                    "nie", "xiao", "ca", "li", "chan", "chai", "li", "yi",
                    "luo", "nang", "zan", "su", "xi", "none", "jian", "za",
                    "zhu", "lan", "nie", "nang", "none", "none", "wei", "hui",
                    "yin", "qiu", "si", "nin", "jian,nan", "hui", "xin", "yin",
                    "nan", "tuan", "tuan", "dun,tun", "kang", "yuan", "jiong",
                    "pian", "yun", "cong,chuang", "hu", "hui", "yuan", "e",
                    "guo", "kun", "cong", "wei", "tu", "wei", "lun", "guo",
                    "jun", "ri", "ling", "gu", "guo", "tai", "guo", "tu",
                    "you", "guo", "yin", "hun", "pu", "yu", "han", "yuan",
                    "lun", "quan,juan", "yu", "qing", "guo", "chui", "wei",
                    "yuan", "quan,juan", "ku", "pu", "yuan", "yuan", "e",
                    "tu,shu,guan", "tu", "tu", "tuan", "lu:e", "hui", "yi",
                    "yuan,huan", "luan", "luan", "tu", "ya", "tu", "ting",
                    "sheng", "yan", "lu", "none", "ya", "zai", "wei,xu", "ge",
                    "yu", "wu", "gui", "pi", "yi", "di,de", "qian", "qian",
                    "zhen", "zhuo,shao", "dang", "qia", "none", "none",
                    "kuang", "chang", "qi,yin", "nie", "mo", "ji", "jia",
                    "zhi", "zhi", "ban", "xun", "tou", "qin", "fen", "jun,yun",
                    "keng", "dun", "fang", "fen", "ben", "tan", "kan",
                    "huai,pi,pei", "zuo", "keng", "bi", "xing", "di", "jing",
                    "ji", "kuai", "di", "jing", "jian", "tan", "li", "ba",
                    "wu", "fen", "zhui", "po", "pan", "tang", "kun", "qu",
                    "tan", "zhi", "tuo", "gan", "ping", "dian", "wa", "ni",
                    "tai", "pi", "jiong", "yang", "fo", "ao", "liu", "qiu",
                    "mu", "ke", "gou", "xue", "ba", "chi,di", "che", "ling",
                    "zhu", "fu", "hu", "zhi", "chui", "la", "long", "long",
                    "lu", "ao", "none", "pao", "none", "xing", "tong,dong",
                    "ji", "ke", "lu", "ci", "chi", "lei", "gai", "yin", "hou",
                    "dui", "zhao", "fu", "guang", "yao", "duo", "duo", "gui",
                    "cha", "yang", "yin", "fa", "gou", "yuan", "die", "xie",
                    "ken", "shang", "shou", "e", "none", "dian", "hong", "ya",
                    "kua", "da", "none", "dang", "kai", "none", "nao", "an",
                    "xing", "xian", "huan,yuan", "bang", "pei", "ba", "yi",
                    "yin", "han", "xu", "chui", "cen", "geng", "ai", "peng",
                    "fang", "que", "yong", "jun", "jia", "di", "mai,man",
                    "lang", "xuan", "cheng", "shan", "jin", "zhe", "lie,le",
                    "lie", "pu,bu", "cheng", "none", "bu", "shi", "xun", "guo",
                    "jiong", "ye", "nian", "di", "yu", "bu", "wu,ya", "juan",
                    "sui", "pi,bei,bi", "cheng", "wan", "ju", "lun", "zheng",
                    "kong", "zhong", "dong", "dai", "tan", "an", "cai", "shu",
                    "beng", "kan", "zhi", "duo", "yi", "zhi", "yi", "pei",
                    "ji", "zhun", "qi", "sao", "ju", "ni", "ku,jue", "ke",
                    "tang", "kun", "ni", "jian", "dui,zui", "jin", "gang",
                    "yu", "e,wu", "peng,beng", "gu", "tu", "leng,ling", "none",
                    "ya", "qian", "none", "an", "chen", "duo,hui", "nao", "tu",
                    "cheng", "yin", "hun", "bi", "lian", "guo", "die", "zhuan",
                    "hou", "bao,bu,pu", "bao", "yu", "di,ti", "mao", "jie",
                    "ruan", "e,ai", "geng", "kan", "zong", "yu", "huang", "e",
                    "yao", "yan", "bao", "ji", "mei", "chang", "du", "tuo",
                    "an", "feng", "zhong", "jie", "zhen", "heng", "gang",
                    "chuan", "jian", "none", "lei", "gang", "huang", "leng",
                    "duan", "wan", "xuan", "ji", "ji", "kuai", "ying", "ta",
                    "cheng", "yong", "kai", "su", "su", "shi", "mi", "ta,da",
                    "weng", "cheng", "tu", "tang", "qiao", "zhong", "li",
                    "peng", "bang", "sai,se", "zang", "dui", "tian", "wu",
                    "cheng", "xun,xuan", "ge", "zhen", "ai", "gong", "yan",
                    "kan", "tian", "yuan", "wen", "xie", "liu", "none", "lang",
                    "chang", "peng", "beng", "chen", "lu", "lu", "ou", "qian",
                    "mei", "mo", "zhuan", "shuang", "shu", "lou", "chi", "man",
                    "biao", "jing", "ce", "shu", "di", "zhang", "kan", "yong",
                    "dian", "chen", "zhi", "ji", "guo", "qiang", "jin", "di",
                    "shang", "mu", "cui", "yan", "ta,da", "zeng", "qi",
                    "qiang", "liang", "none", "zhui", "qiao", "zeng", "xu",
                    "shan", "shan", "ba", "pu", "kuai", "dong", "fan", "que",
                    "mo", "dun", "dun", "zun", "zui", "sheng", "duo,hui",
                    "duo", "tan", "deng,yan", "mu", "fen", "huang", "tan",
                    "da", "ye", "chu", "none", "ao", "qiang", "ji", "qiao",
                    "ken", "yi", "pi", "bi", "dian", "jiang", "ye", "yong",
                    "xue", "tan", "lan", "ju", "huai,pi", "dang", "rang",
                    "qian", "xuan", "lan", "mi", "he,huo", "kai", "ya", "dao",
                    "hao", "ruan", "none", "lei", "kuang", "lu", "yan", "tan",
                    "wei", "huai,pi", "long", "long", "rui", "li", "lin",
                    "rang", "chan", "xun", "yan", "lei", "ba", "none", "shi",
                    "ren", "none", "zhuang", "zhuang", "sheng", "yi", "mai",
                    "qiao,ke", "zhu", "zhuang", "hu", "hu", "kun", "yi", "hu",
                    "xu", "kun", "shou", "mang", "zun", "shou", "yi", "zhi",
                    "gu", "chu", "xiang", "feng", "bei", "none", "bian", "sui",
                    "qun", "ling", "fu", "zuo", "xia,jia", "xiong", "none",
                    "nao", "xia", "kui", "xi", "wai", "yuan", "mao", "su",
                    "duo", "duo", "ye", "qing", "none", "gou", "gou", "qi",
                    "meng", "meng", "yin", "huo", "chen", "da,dai", "ze",
                    "tian", "tai", "fu", "guai", "yao", "yang", "hang,ben",
                    "gao", "shi", "ben,tao", "tai", "tou", "yan", "bi", "yi",
                    "kua", "jia,ga", "duo", "none", "kuang", "yun", "jia",
                    "ba", "en,mang", "lian", "huan", "di", "yan", "pao",
                    "juan", "qi,ji", "nai", "feng", "xie", "fen", "dian",
                    "none", "kui", "zou", "huan", "qi,xie,qie", "kai", "she",
                    "ben", "yi", "jiang", "tao", "zhuang,zang", "ben", "xi",
                    "huang", "fei", "diao", "sui", "beng", "dian", "ao", "she",
                    "weng", "pan", "ao", "wu", "ao", "jiang", "lian", "duo",
                    "yun", "jiang", "shi", "fen", "huo", "bei", "lian", "che",
                    "nu:,ru", "nu", "ding", "nai", "qian", "jian", "ta", "jiu",
                    "nan", "cha", "hao", "xian", "fan", "ji", "shuo", "ru",
                    "fei", "wang", "hong", "zhuang", "fu", "ma", "dan", "ren",
                    "fu", "jing", "yan", "xie", "wen", "zhong", "pa", "du",
                    "ji", "keng", "zhong", "yao", "jin", "yun", "miao", "pei",
                    "chi", "yue", "zhuang", "niu", "yan", "na", "xin", "fen",
                    "bi", "yu", "tuo", "feng", "yuan", "fang", "wu", "yu",
                    "gui", "du", "ba", "ni", "zhou", "zhou", "zhao", "da",
                    "nai,ni", "yuan", "tou", "xuan", "zhi", "e", "mei", "mo",
                    "qi", "bi", "shen", "qie", "e", "he", "xu", "fa", "zheng",
                    "ni", "ban", "mu", "fu", "ling", "zi", "zi", "shi", "ran",
                    "shan", "yang", "qian", "jie", "gu", "si", "xing", "wei",
                    "zi", "ju", "shan", "pin", "ren", "yao", "tong", "jiang",
                    "shu", "ji", "gai", "shang", "kuo", "juan", "jiao", "gou",
                    "lao,mu", "jian", "jian", "yi", "nian", "zhi", "ji", "ji",
                    "xian", "heng", "guang", "jun", "kua", "yan", "ming",
                    "lie", "pei", "yan", "you", "yan", "cha", "xian", "yin",
                    "chi", "gui", "quan", "zi", "song", "wei", "hong", "wa",
                    "lou", "ya", "rao", "jiao", "luan", "ping", "xian", "shao",
                    "li", "cheng", "xie", "mang", "none", "suo", "mu", "wei",
                    "ke", "lai", "chuo", "ding", "niang", "keng", "nan", "yu",
                    "na,nuo", "pei", "sui", "juan", "shen,chen,zhen", "zhi",
                    "han", "di", "zhuang", "e", "pin", "tui", "xian",
                    "mian,wan", "wu", "yan", "wu", "xi", "yan", "yu", "si",
                    "yu", "wa", "li", "xian", "ju", "qu", "chui", "qi", "xian",
                    "zhui", "dong", "chang", "lu", "ai", "e", "e", "lou,lu:",
                    "mian", "cong", "pou", "ju", "po", "cai", "ling", "wan",
                    "biao", "xiao", "shu", "qi", "hui", "fu", "wo", "rui",
                    "tan", "fei", "none", "jie", "tian", "ni", "quan", "jing",
                    "hun", "jing", "qian", "dian", "xing", "hu", "wan", "lai",
                    "bi", "yin", "chou,zhou", "chuo", "fu", "jing", "lun",
                    "yan", "lan", "kun", "yin", "ya", "none", "li", "dian",
                    "xian", "none", "hua", "ying", "chan", "shen", "ting",
                    "yang", "yao", "wu", "nan", "chuo", "jia", "tou", "xu",
                    "yu", "wei", "ti", "rou", "mei", "dan", "ruan", "qin",
                    "none", "wu", "qian", "chun", "mao", "fu", "jie", "duan",
                    "xi", "zhong", "mei", "huang", "mian", "an", "ying",
                    "xuan", "none", "wei", "mei", "yuan", "zhen", "qiu",
                    "ti,shi", "xie", "tuo", "lian", "mao", "ran", "si", "pian",
                    "wei", "wa", "jiu", "hu", "ao", "none", "bao", "xu", "tou",
                    "gui", "zou", "yao", "pi", "xi", "yuan", "ying", "rong",
                    "ru", "chi", "liu", "mei", "pan", "ao", "ma", "gou", "kui",
                    "qin", "jia", "sao", "zhen", "yuan", "cha", "yong", "ming",
                    "ying", "ji", "su", "niao", "xian", "tao,yao", "pang",
                    "lang", "niao", "bao", "ai", "pi", "pin", "yi", "piao",
                    "yu", "lei", "xuan", "man", "yi", "zhang", "kang", "yong",
                    "ni", "li", "di", "gui", "yan", "jin", "zhuan", "chang",
                    "ce", "han,ran", "nen", "lao", "mo", "zhe", "hu", "hu",
                    "ao", "nen", "qiang", "none", "bi", "gu", "wu", "qiao",
                    "tuo", "zhan", "mao", "xian", "xian", "mo", "liao", "lian",
                    "hua", "gui", "deng", "zhi", "xu", "none", "hua", "xi",
                    "hui", "rao", "xi", "yan", "chan", "jiao", "mei", "fan",
                    "fan", "xian", "yi", "wei", "chan", "fan", "shi", "bi",
                    "shan", "sui", "qiang", "lian", "huan,qiong,xuan", "none",
                    "niao", "dong", "yi", "can", "ai", "niang", "ning", "ma",
                    "tiao", "chou", "jin", "ci", "yu", "pin", "none", "xu",
                    "nai", "yan", "tai", "ying", "can", "niao", "none", "ying",
                    "mian", "none", "ma", "shen", "xing", "ni", "du", "liu",
                    "yuan", "lan", "yan", "shuang", "ling", "jiao", "niang",
                    "lan", "xian", "ying", "shuang", "shuai", "quan", "mi",
                    "li", "luan", "yan", "zhu", "lan", "zi", "jie", "jue",
                    "jue", "kong", "yun", "zi", "zi", "cun", "sun", "fu",
                    "bei,bo", "zi", "xiao", "xin", "meng", "si", "tai", "bao",
                    "ji", "gu", "nu", "xue", "none", "chan", "hai", "luan",
                    "sun", "nao", "mie", "cong", "jian", "shu", "chan,can",
                    "ya", "zi", "ni", "fu", "zi", "li", "xue,xiao", "bo", "ru",
                    "nai", "nie", "nie", "ying", "luan", "mian", "ning",
                    "rong", "ta", "gui", "zhai,zhe", "qiong", "yu", "shou",
                    "an", "tu", "song", "wan", "rou", "yao", "hong", "yi",
                    "jing", "zhun", "mi", "guai", "dang", "hong", "zong",
                    "guan", "zhou", "ding", "wan,yuan", "yi", "bao", "shi",
                    "shi", "chong", "shen", "ke", "xuan", "shi", "you", "huan",
                    "yi", "tiao", "shi", "xian", "gong", "cheng", "qun",
                    "gong", "xiao", "zai", "zha", "bao", "hai", "yan", "xiao",
                    "jia", "shen", "chen", "rong", "huang", "mi", "kou",
                    "kuan", "bin", "su,xiu", "cai,shen", "zan", "ji", "yuan",
                    "ji", "yin", "mi", "kou", "qing", "he", "zhen", "jian",
                    "fu", "ning", "bing", "huan", "mei", "qin", "han", "yu",
                    "shi", "ning", "jin", "ning", "zhi", "yu", "bao", "kuan",
                    "ning", "qin", "mo", "cha", "ju", "gua", "qin", "hu", "wu",
                    "liao", "shi", "ning", "zhai", "shen", "wei", "xie",
                    "kuan", "hui", "liao", "jun", "huan", "yi", "yi", "bao",
                    "qin", "chong", "bao", "feng", "cun", "dui", "si",
                    "xun,xin", "dao", "lu:,luo", "dui", "shou", "po", "feng",
                    "zhuan", "fu", "she,shi,ye", "ke", "jiang,qiang",
                    "jiang,qiang", "zhuan", "wei,yu", "zun", "xun,xin", "shu",
                    "dui", "dao", "xiao", "ji", "shao", "er", "er", "er", "ga",
                    "jian", "shu", "chen", "shang", "shang", "yuan", "ga",
                    "chang", "liao", "xian", "xian", "none", "wang,you",
                    "wang,you", "you", "liao", "liao", "yao", "mang,pang",
                    "wang", "wang", "wang", "ga", "yao", "duo", "kui", "zhong",
                    "jiu", "gan", "gu", "gan", "gan", "gan", "gan", "shi",
                    "yin", "chi,che", "kao", "ni", "jin", "wei,yi", "niao,sui",
                    "ju", "pi", "ceng", "xi", "bi", "ju,ji", "jie", "tian",
                    "qu", "ti", "jie", "wu", "diao", "shi", "shi", "ping,bing",
                    "ji", "xie", "chen", "xi", "ni", "zhan", "xi", "none",
                    "man", "e", "lou", "ping", "ti", "fei", "shu,zhu", "xie",
                    "tu", "lu:", "lu:", "xi", "ceng", "lu:", "ju", "xie", "ju",
                    "jue", "liao", "jue", "shu,zhu", "xi", "che", "tun,zhun",
                    "ni", "shan", "wa", "xian", "li", "e", "none", "none",
                    "long", "yi,ge", "qi", "ren", "wu", "han", "shen", "yu",
                    "chu", "sui", "qi", "none", "yue", "ban", "yao", "ang",
                    "ya", "wu", "jie", "e", "ji", "qian", "fen", "wan", "qi",
                    "cen", "qian", "qi", "cha", "jie", "qu", "gang", "xian",
                    "ao", "lan", "dao", "ba", "zhai", "zuo", "yang", "ju",
                    "gang", "ke", "gou", "xue", "bo", "li", "tiao", "qu",
                    "yan", "fu", "xiu", "jia", "ling", "tuo", "pei", "you",
                    "dai", "kuang", "yue", "qu", "hu", "po", "min", "an",
                    "tiao", "ling", "chi", "none", "dong", "none", "kui",
                    "xiu", "mao", "tong", "xue", "yi", "none", "he", "ke",
                    "luo", "e", "fu", "xun", "die", "lu", "lang", "er", "gai",
                    "quan", "tong,dong", "yi", "mu", "shi", "an", "wei", "hu",
                    "zhi,shi", "mi", "li", "ji", "tong", "kui", "you", "none",
                    "xia", "li", "yao", "jiao,qiao", "zheng", "luan", "jiao",
                    "e", "e", "yu", "ye", "bu", "qiao", "qun", "feng", "feng",
                    "nao", "li", "you", "xian", "hong", "dao", "shen", "cheng",
                    "tu", "geng", "jun", "hao", "xia", "yin", "wu,yu", "lang",
                    "kan", "lao", "lai", "xian", "que", "kong", "chong",
                    "chong", "ta", "none", "hua", "ju", "lai", "qi", "min",
                    "kun", "kun", "zu", "gu", "cui", "ya", "ya,ai", "gang",
                    "lun", "lun", "leng", "jue", "duo", "cheng", "guo", "yin",
                    "dong", "han", "zheng", "wei", "yao,xiao", "pi", "yan",
                    "song", "jie", "beng", "zu", "jue", "dong", "zhan", "gu",
                    "yin", "zi", "ze", "huang", "yu", "wei,wai", "yang",
                    "feng", "qiu", "dun", "ti", "yi", "zhi", "shi", "zai",
                    "yao", "e", "zhu", "kan", "lu:", "yan", "mei", "gan", "ji",
                    "ji", "huan", "ting", "sheng", "mei", "qian,kan", "wu",
                    "yu", "zong", "lan", "jie,he", "yan", "yan", "wei", "zong",
                    "cha", "sui", "rong", "ke", "qin", "yu", "qi", "lou", "tu",
                    "dui", "xi", "weng", "cang", "dang", "rong", "jie", "ai",
                    "liu", "wu", "song", "qiao", "zi", "wei", "beng", "dian",
                    "cuo", "qian", "yong", "nie", "cuo", "ji", "none", "none",
                    "song", "zong", "jiang", "liao", "none", "chan", "di",
                    "cen", "ding", "tu,die", "lou", "zhang", "zhan", "zhan",
                    "ao", "cao", "qu", "qiang", "zui", "zui", "dao", "dao",
                    "xi", "yu", "bo", "long", "xiang", "ceng", "bo", "qin",
                    "jiao", "yan", "lao", "zhan", "lin", "liao", "liao", "jin",
                    "deng", "duo", "zun", "jiao,qiao", "gui", "yao", "qiao",
                    "yao", "jue", "zhan", "yi", "xue", "nao", "ye", "ye", "yi",
                    "e", "xian", "ji", "xie", "ke", "sui", "di", "ao", "zui",
                    "none", "yi", "rong", "dao", "ling", "za", "yu", "yue",
                    "yin", "none", "jie", "li", "sui,xi", "long", "long",
                    "dian", "ying", "xi", "ju", "chan", "ying", "kui", "yan",
                    "wei", "nao", "quan", "chao", "cuan", "luan", "dian",
                    "dian", "nie", "yan", "yan", "yan", "nao", "yan", "chuan",
                    "gui", "chuan", "zhou", "huang", "jing", "xun", "chao",
                    "chao", "lie", "gong", "zuo", "qiao", "ju", "gong", "none",
                    "wu", "none", "none", "cha,chai,ci", "qiu", "qiu", "ji",
                    "yi", "si", "ba", "zhi", "zhao", "xiang,hang", "yi", "jin",
                    "xun", "juan", "none", "xun", "jin", "fu", "za", "bi",
                    "shi", "bu", "ding", "shuai", "fan", "nie", "shi", "fen",
                    "pa", "zhi", "xi", "hu", "dan", "wei", "zhang", "tang",
                    "dai", "ma", "pei", "pa", "tie", "fu", "lian", "zhi",
                    "zhou", "bo", "zhi", "di", "mo", "yi", "yi", "ping", "qia",
                    "juan", "ru", "shuai,shuo", "dai", "zhen", "shui", "qiao",
                    "zhen", "shi", "qun", "xi", "bang", "dai", "gui",
                    "chou,dao", "ping", "zhang", "sha", "wan", "dai", "wei",
                    "chang", "sha", "qi", "ze", "guo", "mao", "du", "hou",
                    "zhen,zheng", "xu", "mi", "wei", "wo", "fu", "yi", "bang",
                    "ping", "none", "gong", "pan", "huang", "dao,tao", "mi",
                    "jia", "teng", "hui", "zhong", "sen", "man", "mu", "biao",
                    "guo", "ze", "mu", "bang", "zhang", "jiong", "chan", "fu",
                    "zhi", "hu", "fan", "chuang,zhuang", "bi", "bi", "none",
                    "mi"
            };
        }
    }
}
